### ISSUE TITLE
XCM Helper pallet: moving asset transfer into update_total_reserves

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#1002]
Regarding #954 
Suggest moving this code inside into `T::XCM::update_total_reserves`
https://github.com/parallel-finance/parallel/blob/2d5382a471e2a0ce0b04579af662f37830d23fb9/pallets/crowdloans/src/lib.rs#L500-L506

because it's not good to make the transfer in one pallet, however, keep accounts in another one.

**Comment by GopherJ** [comment]
done
