### ISSUE TITLE
Prepare xcm fees when user stakes

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1064]

**Comment by GopherJ** [comment]
Crowdloans pallet uses `par/fees` account to pay for xcm fees.

pallet-liquid-staking we want the users to pay for xcm fees, so we need to charge users for fees.

after #1038 #1063, we don't use InsurancePool to pay for xcm fees anymore. we need to call `pallet-xcm-helper`'s `add_xcm_fees` to transfer the charged xcm fees from user to `pallet-xcm-helper`

**Comment by alannotnerd** [comment]
As current version, we only charge once. And it should cover all fees.

**Comment by GopherJ** [comment]
done, now we just add_xcm_fees
