### ISSUE TITLE
Internal pallet-crowdloans review

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1085]

**Comment by MrPai** [comment]
### 1.1
if already contribute by XCM, why still need update pending
https://github.com/parallel-finance/parallel/blob/ccf9f1a938/pallets/crowdloans/src/lib.rs#L427-L432

### 1.2
method like `set_vrfs/close/reopen/auction_succeeded/...` should be called manually or by an offchain-client?

### 1.3
Just confirm: `res.is_none() == true` means xcm execute succeed?
https://github.com/parallel-finance/parallel/blob/ccf9f1a938/pallets/crowdloans/src/lib.rs#L662

**Comment by GopherJ** [comment]
## 1.1

do_contribute will only send XCM but dont do any mutation on the storage. update_pending is for accumulating user's contribution to the pending childstorage. If the XCM is executed successfully on the relaychain then this contribution will go from `pending` storage to `contributed` field.

**Comment by GopherJ** [comment]
## 1.2

not they should be called by governance

**Comment by GopherJ** [comment]
## 1.3

currently `migrate_pending` should only be called when there is no xcm in flight. So we shouldn't have `do_contribute` while executing `migrate_pending`.

`migrate_pending` is then only allowed to be executed in `Pending` OR `Closed` phase when we are sure that no XCM is in flight, all XCM are already succeeded or failed. In this case, pending should only include unsent contributions. we can then call `migrate_pending` to help sending XCMs and mutate the storage after receiving the reply

**Comment by MrPai** [comment]
- goverance call
- true/false for add/minus
- xcm safety check

**Comment by alannotnerd** [comment]
Do we have a PRD? I'm kind of confused by the process.

**Comment by GopherJ** [comment]
> * goverance call (manually?)
Yes now we need to manually to call `migrate_pending`, `open`, `close`, `reopen`, `auction_failed`, `auction_succeeded`, `slot_expired`


> 
>     * xcm safety check
2016 is special, the real xcm safety issue is: https://github.com/paritytech/polkadot/issues/4623

> 
>     * child storage safety check and data analysis (how to query?)

blocked by @rjman-ljm 's script


>     * check xcm-notify and storage change
the others can be tested but childstorage check is still blocked

**Comment by GopherJ** [comment]
> Do we have a PRD? I'm kind of confused by the process. For example, should we must call `migarate_pending` before calling `open`? why should we do this? and what those statuses mean?

we have only: https://www.notion.so/parallelfinance/Pallet-crowdloans-a99c871af7044505bccff347fa97dbef and https://www.notion.so/parallelfinance/Crowdloan-71a8bff983824ccabc4fd3ed47a14b2f

**Comment by MrPai** [comment]
if `2016` is in VRF, but `2008` is not,  then users can not contribute `2008` while `XCM` according to this code: 
**contribute()**  
```
if vault.phase == VaultPhase::Contributing && !Self::has_vrfs() {
                Self::do_contribute(&who, crowdloan, amount)?;
            }
```
And what if `2008`'s phase is `VaultPhase::Contributing`, then this doesn't work too, because:
**migrate_pending()**
```
ensure!(
                vault.phase == VaultPhase::Pending || vault.phase == VaultPhase::Closed,
                Error::<T>::IncorrectVaultPhase
            );
```

**Comment by rjman-ljm** [comment]
> > * goverance call (manually?)
> >   Yes now we need to manually to call `migrate_pending`, `open`, `close`, `reopen`, `auction_failed`, `auction_succeeded`, `slot_expired`
> 
> > ```
> > * xcm safety check
> > ```
> 
> 2016 is special, the real xcm safety issue is: [paritytech/polkadot#4623](https://github.com/paritytech/polkadot/issues/4623)
> 
> > ```
> > * child storage safety check and data analysis (how to query?)
> > ```
> 
> blocked by @rjman-ljm 's script
> 
> > ```
> > * check xcm-notify and storage change
> > ```
> 
> the others can be tested but childstorage check is still blocked

how is it going, maybe I can try to solve it. [dump-script](https://github.com/parallel-finance/dump-crowdloan)

**Comment by GopherJ** [comment]
> > > * goverance call (manually?)
> > >   Yes now we need to manually to call `migrate_pending`, `open`, `close`, `reopen`, `auction_failed`, `auction_succeeded`, `slot_expired`
> > 
> > 
> > > ```
> > > * xcm safety check
> > > ```
> > 
> > 
> > 2016 is special, the real xcm safety issue is: [paritytech/polkadot#4623](https://github.com/paritytech/polkadot/issues/4623)
> > > ```
> > > * child storage safety check and data analysis (how to query?)
> > > ```
> > 
> > 
> > blocked by @rjman-ljm 's script
> > > ```
> > > * check xcm-notify and storage change
> > > ```
> > 
> > 
> > the others can be tested but childstorage check is still blocked
> 
> [dump-script](https://github.com/parallel-finance/dump-crowdloan), seems I need to review pallet_crowdloan first.

Yes @rjman-ljm pls also do a review

**Comment by GopherJ** [comment]
> ### 2.1
> 
> if `2016` is in VRF, but `2008` is not, then users can not contribute `2008` while `XCM` according to this code: **contribute()**
> 
No users should be able to contribute `2008` 
> ```
> if vault.phase == VaultPhase::Contributing && !Self::has_vrfs() {
>                 Self::do_contribute(&who, crowdloan, amount)?;
>             }
> ```
> 
> And what if `2008`'s phase is `VaultPhase::Contributing`, then this doesn't work too, because: **migrate_pending()**
> 
> ```
> ensure!(
>                 vault.phase == VaultPhase::Pending || vault.phase == VaultPhase::Closed,
>                 Error::<T>::IncorrectVaultPhase
>             );
> ```
>

**Comment by GopherJ** [comment]
> ### 2.2
> 
> in `claim_refund` method, according to the following code:
> 
> ```
> T::Assets::transfer(
>                 T::RelayCurrency::get(),
>                 &Self::vault_account_id(crowdloan),
>                 &who,
>                 amount,
>                 false,
>             )?;
> ```
> 
> My question is how can we guarantee that users have enough assets to claim and if it's possible that `&Self::vault_account_id(crowdloan)` do not have enough assets? Not sure if this is a question.

because we check if vault is in `Failed` or `Expired` phase, if vault can pass from `Closed` phase to `Failed` or `Expired`, then that means `auction_failed` or `slot_expired` has been called by the governance. In these two calls we send `xcm.Transact(crowdloan.withdraw(2012)` to relaychain to withdraw contributions, once we received the XCM's notification then we can mint tokens into `vault_account_id`, so in this case when users come to claim, they should be able to claim back their tokens

**Comment by GopherJ** [comment]
> ### 2.3
> 
> in method `do_migrate_pending`:
> 
> ```
> vault.contributed = vault
>                 .contributed
>                 .checked_add(amount)
>                 .ok_or(ArithmeticError::Overflow)?;
> let (contributed, _) = Self::contribution_get(vault.trie_index, who, false);
> let new_contributed = contributed
>                 .checked_add(amount)
>                 .ok_or(ArithmeticError::Overflow)?;
> ```
> 
> seems like `vault.contributed` equals to `contributed`, so no need to call `Self::contribution_get(vault.trie_index, who, false);`, does that right?

no `vault.contributed` is the sum of all contributions (succeeded on relaychain), but `Self::contribution_get(...)` only means the contribution of `who`. Since the 3rd argument is `false`, which means `who's` contributed

**Comment by MrPai** [comment]
if call `auction_failed` to mark its phase as `VaultPhase::Failed`, then no way to reopen it, this fits the relaychain crowdloan mechanism, does it right?

**Comment by GopherJ** [comment]
> if call `auction_failed` to mark its phase as `VaultPhase::Failed`, then no way to reopen it, this fits the relaychain crowdloan mechanism, does it right?

Yes some phase cannot go back.

**Comment by alannotnerd** [comment]
I cannot find any usage of the `Vec` in contritution storage. Why should we use that?

**Comment by rjman-ljm** [comment]
# Review

## Review crowdloan pallet

1. Simple question, I was confused by similar variable names.
   
   ![confused-1](https://cdn.jsdelivr.net/gh/rjman-ljm/resources@master/assets/16408596342271640859634025.png)
   > This is an accumulation of trie_index, I think it would be better to extract this action to a function
2. I think the [cap verification](https://github.com/parallel-finance/parallel/blob/ccf9f1a938/pallets/crowdloans/src/lib.rs#L425) should happen before `T::Assets::transfer`
3. I made an analysis of the life cycle of the phase, we can check that the transfers of states is logical. Especially, consider whether there are state transitions that are not taken into account.
   
    ![vault-phase](https://cdn.jsdelivr.net/gh/rjman-ljm/resources@master/assets/1640891716620crowdloan_vault.drawio.png)
4. `open`, `reopen`, `close`, `auction_succeeded`, `auction_failed` do very similar jobs, but has different call_name, can we use an **enumeration** parameter, and then match the enumeration to reduce these to a single call? like the following `change_phase`, although it may look like a complex function body, but I think it looks clearer and is easier to call by the front-end.

```rust
        pub fn change_phase(
            origin: OriginFor<T>,
            crowdloan: ParaId,
            old_phase: VaultPhase,
            new_phase: VaultPhase,
        ) -> DispatchResult {
            match new_phase {
                VaultPhase::Pending => { unimplemented!(); },
                VaultPhase::Contributing => {
                    match old_phase {
                        VaultPhase::Pending => {
                            T::OpenCloseOrigin::ensure_origin(origin)?;
                            todo!();
                        },
                        VaultPhase::Closed => {
                            
                        },
                        _ => todo!(),
                    }
                },
                VaultPhase::Closed => todo!(),
                VaultPhase::Succeeded => todo!(),
                _ => { unimplemented!(); },
            }
            
            // log::trace!(
            //     target: "crowdloans::TODO:changed_phase",
            //     "pre-toggle. crowdloan: {:?}",
            //     crowdloan,
            // );

            Ok(())
        }
```

5. `do_migrate_pending` is of great importance and I'd like to know that if `res.is_none()` can cover the cases of execution in relaychain. If it's certain, then there's no problem.

![sub](https://cdn.jsdelivr.net/gh/rjman-ljm/resources@master/assets/1640893929361image-20211231024117093.png)

6. Optimization
   - [ ] More code comments, since the underlying logic is actually complex
   - [ ] extract some code into functions(Or maybe not)
7. The others LGTM.

**Comment by GopherJ** [comment]
> I cannot find any usage of the `Vec` in contritution storage. Why should we use that?

it's for adding memo, but currently we dont use memo

**Comment by GopherJ** [comment]
> 



> 1. I think the [cap verification](https://github.com/parallel-finance/parallel/blob/ccf9f1a938/pallets/crowdloans/src/lib.rs#L425) should happen before [T::Assets::transfer](https://github.com/parallel-finance/parallel/blob/ccf9f1a938/pallets/crowdloans/src/lib.rs#L414)
> 
>     2. I made an analysis of the life cycle of the phase, we can check that the transfers of states is appropriate. Especially, consider whether there are state transitions that are not taken into account.
>        ![vault-phase](https://camo.githubusercontent.com/405491aee4cbb718103f941f7b98388962ded580789ad8c56a419a389cc8a4d7/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f726a6d616e2d6c6a6d2f7265736f7572636573406d61737465722f6173736574732f3136343038393137313636323063726f77646c6f616e5f7661756c742e64726177696f2e706e67)
> 
>     3. `open`, `reopen`, `close`, `auction_succeeded`, `auction_failed` do very similar jobs, but has different call_name, can we use an **enumeration** parameter, and then match the enumeration to reduce these to a single call? Although it may look like a complex function body, but I think it looks clearer and is easier to call by the front-end.
> 
>     4. `do_migrate_pending` is of great importance and I wanna know that if [res.is_none()](https://github.com/parallel-finance/parallel/blob/ccf9f1a938/pallets/crowdloans/src/lib.rs#L662) can cover the cases of execution in relaychain. If it's certain, then there's no problem.
> 
>     5. The others LGTM.

1. https://github.com/parallel-finance/parallel/pull/1111
2. Good job! I've put in notion
3. Yes we can consider that but for now I think we dont need to change because they all works we can keep current design, I'll consider your idea
4. No, res.is_none() cannot ensure, we will need XCM v3
