### ISSUE TITLE
If we need to add custom RPC for node/parallel?

### ISSUE THREAD

**Issue by RainFallsSilent** [parallel-finance/parallel#110]
It seems that only parallel-dev intend to support custom RPC, If we need to add custom RPC for node/parallel rpc_extensions_builder?

**Comment by GopherJ** [comment]
now it's a default `jsonrpc_core::IoHandler` 
<img width="474" alt="image" src="https://user-images.githubusercontent.com/33961674/118066039-93d96700-b3d0-11eb-9db8-66241e5c2a5e.png">

**Comment by GopherJ** [comment]
https://github.com/parallel-finance/parallel/blob/master/node/parallel/src/service.rs#L323
