### ISSUE TITLE
Deposit VaultContributed/VaultFailed/VaultExpired event only if XCM successfully executed

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1105]

**Comment by GopherJ** [comment]
we should also remove `VaultContributing`, `VaultAuctionFailing`, `VaultSlotExpiring`

**Comment by rjman-ljm** [comment]
> we should also remove `VaultContributing`, `VaultAuctionFailing`, `VaultSlotExpiring`

Sure to remove it? Shouldn't we deposit an event after the call?

**Comment by GopherJ** [comment]
yes @rjman-ljm we may need to record `referral_code` in XcmInflight

**Comment by rjman-ljm** [comment]
> yes @rjman-ljm we may need to record `referral_code` in XcmInflight, but I think we dont need to have events like `withdrawing` because it's not really useful

got it
