### ISSUE TITLE
Limit pallet-crowdloans contribute call's referral_code length

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1113]

**Comment by GopherJ** [comment]
contributor may use big referral_code to attack, we should limit it to specific length

**Comment by ashi20192020ayush** [comment]
@GopherJ Should we define `MaxReferralCode` in config and add a check in contribute call?

**Comment by GopherJ** [comment]
@ashi20192020ayush I think maybe we can test the transaction fee first. If the users need to pay much higher transaction fees with a big referral code. Then I think maybe we dont need to change anything.

If not then we can do what you are saying
