### ISSUE TITLE
Fix polkadotXcm NotifyDispatchError 

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1119]
<img width="703" alt="image" src="https://user-images.githubusercontent.com/33961674/147902526-5ae0e701-e481-4fde-b635-c560b0d4e2b5.png">

**Comment by GopherJ** [comment]
This now starts to happen while calling `migrate_pending`

**Comment by MrPai** [comment]
![image](https://user-images.githubusercontent.com/26266313/148005944-2e2f2712-ac48-4436-bae7-23589250eeb4.png)

**Comment by GopherJ** [comment]
@MrPai yes but it doesn't make sense actually

**Comment by GopherJ** [comment]
I tried to dump pending contributions and compare the sum with vault.pending but found they didn't match:

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/33961674/148006089-8a81bc7b-590e-4bef-9a44-f3813cbfd62e.png">
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/33961674/148006101-aeb0226a-4ce5-42d7-a9b2-6b42288ed517.png">

**Comment by MrPai** [comment]
Obviously, `QueryResponse` did not call method `notification_received`, there may be a Decode/Encode error.

**Comment by GopherJ** [comment]
@MrPai yes it's possible

**Comment by GopherJ** [comment]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/33961674/148006707-9cbd4ef6-9d65-4037-85cb-d40b537ed011.png">

**Comment by GopherJ** [comment]
@MrPai acually it's calling `notification_received` but just failed

**Comment by GopherJ** [comment]
@MrPai I pushed a commit to master which may fixes this
