### ISSUE TITLE
Release cDOT-lease only after winning

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1133]
Since we would like to mint cDOT only when vault becomes succeeded. To achieve this, we can mint cDOT in `on_idle` hook instead of `XCM` callback.

However, since we will transfer user's balance to vault_account_id, for the failed ones, then don't have cDOT anymore so they cannot claim cDOT on their own. We will need to add `RefundingVaults` storage and refund DOT to users after failing.

Basically `MintingVaults` and `RefundingVaults` are arrays. They just record the succeeded/failed vaults. When the governance call `auction_succeeded` we should add the vault 's paraid and id to `MintingVaults` after receiving the notification. When the governance call `auction_failed` or `slot_expired` we should add the vault's paraid and id to `RefundingVaults` after receiving the notification.

Then in `on_idle` hook, we can refund to user OR mint cDOT for user using `contribution_iterator`

**Comment by GopherJ** [comment]
This will require adding `refunded` childstorage kind, we scan `contributed` childstorage and refund DOT/KSM to user. Then move this user from `contributed` to `refunded`. once all `contributed` is migrated, we then remove vault from `RefundingVaults`

**Comment by GopherJ** [comment]
This will also require adding `minted` childstorage kind, we scan contributed childstorage and mint cDOT for user. Then move this user from contributed to `minted`. once all contributed is migrated, we then remove vault from MintingVaults

**Comment by GopherJ** [comment]
For the `expired` case, we can also add vault information to `RefundingVaults`, then scan `minted` childstorage and refund DOT/KSM to user, then move this user from contributed to `refunded`. Once all minted is migrated, we then remove vault from RefundingVaults

**Comment by MrPai** [comment]
The process is ok for me, however, I'm not sure `on_idle` can work well as we expect.

**Comment by GopherJ** [comment]
@MrPai or on_initialize and we define a limit like `MaxRefundLimit` etc

**Comment by GopherJ** [comment]
there are still some questions, although users who contributed to failed vaults dont have cDOT but actually their contribution has already been recorded in `contributed` childstorage. they can come to claim and we can also refund for them.

**Comment by GopherJ** [comment]
Another proposal is to add `UnreservingVaults`, we issue cDOT to user after xcm notification.

If the vault is succeeded,  we add the vault to `UnreservingVaults` and then we iterate `contributed` childstorage and unreserve users' cDOT.

if the vault is failed, user can call claim_refund, we will also check `contributed` childstorage and then slash reserved token then mint DOT to user.

**Comment by MrPai** [comment]
How about using a user-claim mode, as we have already marked the ParaId as  one of `Failed/Expired/Succeed`, then if the status is:
**Succeed**: user can only claim cDOT out
**Failed**: user can only claim DOT back
**Expired**: user can only claim DOT back

We only need to expose one `claim` API, let the user claim, and decide by the ParaId's status.

**Comment by GopherJ** [comment]
@MrPai Yes, we have recorded `contributions`, but we will need to update `contributed` childstorage to avoid double-claiming

**Comment by GopherJ** [comment]
Succeed: user can only claim cDOT out => substract contribution from `contributed` childstorage. Issue cDOT
Failed: user can only claim DOT back => substract contribution from `contributed` childstorage. Mint DOT
Expired: user can only claim DOT back => burn cDOT, mint DOT

**Comment by GopherJ** [comment]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/33961674/148353977-b4302a05-c649-4655-b1cc-28b30ea9df9a.png">

**Comment by GopherJ** [comment]
## Interfaces

### Option 1

  1. claim_ctoken(Origin, paraid, leaseStart, leaseEnd)
  2. refund_failed(Origin, paraid, leaseStart, leaseEnd)
  3. refund_expired(Origin, paraid, leaseStart, leaseEnd, amount)
