### ISSUE TITLE
add vaults for batch 1 winning projects (Acala, moonbeam...)

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1135]
based on: https://github.com/parallel-finance/parallel/issues/1086#issuecomment-1004561593

**Comment by GopherJ** [comment]
- [ ] Acala
- [ ] Moonbeam
- [ ] Astar
- [ ] Parallel
- [ ] Clover

**Comment by MrPai** [comment]
### before runtime upgrade
![175](https://user-images.githubusercontent.com/26266313/148886486-8777e856-e48a-4977-bf7e-f52dc39dc566.jpg)

### after runtime upgrade
![176-1](https://user-images.githubusercontent.com/26266313/148886522-db05a496-fd44-4781-8268-dc6fef8f847f.jpg)
![176-2](https://user-images.githubusercontent.com/26266313/148886531-604fa490-af9d-48ad-86e9-8093631f62b0.jpg)

**Comment by GopherJ** [comment]
should be done but just need to merge
