### ISSUE TITLE
allow to dissolve vault

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1141]
When a vault is Closed of Failed we need a method to cleanup the vault.

Cleaning up a vault requires us to refund any contributions to the vault before removing the item from storage.

We’ll need to implement two new extrinsics that 1. allow us to refund contributors and 2. dissolve the vault.

Below details are provided that explain the steps of this process.

**Comment by drbh** [comment]
@GopherJ will the following snippet capture all of the contributors that need to be refunded?

```rust
let completed_contributions =
    Self::contribution_iterator(vault.trie_index, ChildStorageKind::Contributed);

let pending_contributions =
    Self::contribution_iterator(vault.trie_index, ChildStorageKind::Pending);
```

Also, after we refund all of the RelayCurrency, should we/how do we burn all of the vault `ctoken` tokens?

Thanks 🙏

**Comment by GopherJ** [comment]
@drbh yes I'm still thinking and testing about this

**Comment by GopherJ** [comment]
Basically we will need to have two calls:

- `refund`: refund users' contribution, we can define `RemoveKeysLimit` like relaychain and refund everytime `RemoveKeysLimit` contributors. This call will need to be called multiple times
- `dissolve`: dissolve vault after refunding

**Comment by GopherJ** [comment]
we have 3 kinds of childstorages:

- `pending` for gathering users' contributions but dont send any XCM
- `flying` for contribution which has sent XCM but no response yet
- `cotributed` for contribution which happened on relaychain

**Comment by GopherJ** [comment]
after cleaning `contributed` childstorage and `pending` childstorage. We can then call `dissolve` to remove a crowdloan.

this will do a few things:

1. check if `pending` and `contributed` childstorages have been cleaned
2. remove vault
3. remove `(leaseStart, leaseEnd)` from `LeasesRegistry`

**Comment by GopherJ** [comment]
@drbh @c02fee pls check this to see if you have questions

**Comment by c02fee** [comment]
Hi @drbh @GopherJ 

Would like to know more info about this  user story

**Comment by drbh** [comment]
@c02fee do you have a specific question? 

I think we should be able to start a draft pr with the new extrinsic/variables shared above? If you'd like I can open a PR with some stubs where we need to add new logic? Please let me know how I can help you get started!

**Comment by GopherJ** [comment]
@c02fee feel free to reach me for more context.

**Comment by c02fee** [comment]
Needs information on 
* What is RemoveKeyLimit?
* Whats the mechanism behind this function `kill contribution util reached RemoveKeysLimit` ?
* Which function required to return ? `if reached limit then return the function`
* `if no and we already cleaned pending childstorage. Then we scan contributed childstorage and mint RelayCurrency and kill contribution for contributor util reached RemoveKeysLimit.` For this from where it should get individual amounts ?
@GopherJ @drbh

**Comment by drbh** [comment]
Hey @c02fee 

RemoveKeyLimit is simply a limit of how many keys we’ll remove at one time when the refund extrinsic is called. This variable configured at the pallet level and is defined on the runtime which can be found here: https://github.com/parallel-finance/parallel/blob/a4a11e26aad55b76cda34de6468f4983d124b201/pallets/crowdloans/src/mock.rs#L370

ChildStorage is referring to the way that contributions are stored inside of the pallet. Each contributor has “a child storage” that maintains a record of all of the Pending, Flying and Contributed amounts for each user.

The refund function should return when we 1. Have refunded all of the contributions or 2. When the RemoveKeyLimit is reached.

**Comment by c02fee** [comment]
@drbh so its  the `ChildStorageKind` enum,

**Comment by c02fee** [comment]
@GopherJ  I'm unclear about this ? the  point 3 ? /
// 3. if reached limit then return the `function`
Which function referring to ?

**Comment by c02fee** [comment]
@GopherJ  @drbh 

Questions regarding these points

// 2. scan pending childstorage, mint RelayCurrency for contributor and kill contribution util reached RemoveKeysLimit.
Implementation 
```
let (amount, _) = Self::contribution_get(vault.trie_index, &who, ChildStorageKind::Pending);
ensure!(!amount.is_zero(), Error::<T>::NoContributions);
T::Assets::mint_into(T::RelayCurrency::get(), &who, amount)?;
```
// 3. if reached limit then return the function

Question ? 
* How to get the raise condition to return `the function`? 
*   is it 
```
            Self::deposit_event(Event::<T>::AllRefunded(
            crowdloan
            ));
```
// 4. if no and we already cleaned pending childstorage. Then we scan contributed childstorage and mint RelayCurrency and kill contribution for contributor util reached RemoveKeysLimit.  

Question 
* Whats the difference between point number 2 and point number 4?

**Comment by drbh** [comment]
@c02fee 

I think the code should look similar too 

```rust
// create iterator of all "Pending" contributors to this vault
let contributions =
    Self::contribution_iterator(vault.trie_index, ChildStorageKind::Pending);
let mut refunded_count = 0u32;
let mut all_refunded = true;

// iterate over pending contributions until limi
for (who, (amount, referral_code)) in contributions {
    if refunded_count >= T::RemoveKeysLimit::get() {
        all_refunded = false;
        return Ok(()); // early exit if we met limit
    }

    // mint RelayCurrency back into each users account
    T::Assets::mint_into(T::RelayCurrency::get(), &who, amount)?;

    // kill contributions 
    Self::contribution_kill(vault.trie_index, &who, ChildStorageKind::Pending);              
}

// last line of function
Ok(())
```

In regards to number 3 we can early exit with an error using something like `ensure!(1 == 0, Error::<T>::MyCustomError);` or the function should `return Ok(())` if we want to exit without an error

In regards to how number 4 is different. I think we'll need to repeat the same process (minting/killing) for all of the `ChildStorageKind::Contributed`. But we should only do this after all of the `ChildStorageKind::Pending` are completed

I hope this helps! please let me know if you have more questions

**Comment by GopherJ** [comment]
> @GopherJ I'm unclear about this ? the point 3 ? / // 3. if reached limit then return the `function` Which function referring to ?

return means exit the function

**Comment by GopherJ** [comment]
hi @c02fee is this all clear? this will need to be finished very soon pls
