### ISSUE TITLE
Prepare cDOT mint strategy and script

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1157]

**Comment by MrPai** [comment]
let's use `pallet_assets::mint` to prepare cDOT for users, 
because it's not suggested opening `pallet_assets::transfer` at first stage, and `pallet_assets::force_transfer` need the same privilege like `pallet_assets::mint`.
`pallet_assets::mint` will be an easy option.

**Comment by MrPai** [comment]
WIP: https://github.com/parallel-finance/cdot-mint-script
