### ISSUE TITLE
AMM implement swapExactTokensForTokens, swapTokensForExactTokens

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1180]
`swapExactTokensForTokens`: given amount is fixed, the output token amount is not known in advance
`swapTokensForExactTokens`: the output token amount is fixed, but the input token amount is not kown

**Comment by drbh** [comment]
Relevant Uniswap code

https://github.com/Uniswap/v2-periphery/blob/2efa12e0f2d808d9b49737927f0e416fafa5af68/contracts/UniswapV2Router02.sol#L224-L251

**Comment by drbh** [comment]
in order for these functions to be implemented, we'll need to add two methods; `get_amount_in` and `get_amount_out` to the AMM pallet. 

A the moment we only implement `get_amount_out` as the `trade` function and because of this we can only implement the `swap_exact_tokens_for_tokens` right now.

**Comment by GopherJ** [comment]
yes we may need all those helpers:


 -  quote
 - getAmountOut
 - getAmountIn
 - getAmountsOut
 - getAmountsIn

**Comment by c02fee** [comment]
@drbh @GopherJ   Do we have an implementation for this helper method ? `TransferHelper.safeTransferFrom` it requires in `SwapTokens / SwapExactTokens` methods

**Comment by drbh** [comment]
Hey @c02fee `safeTransferFrom` in Ethereum is similar to `Assets::transfer(...)` in  Substrate. However, I think we may have to implement our logic a bit differently in our pallet. For instance we'll need to implement the `swap` function and export it so the router can implement the functions you mentioned. 

I believe the functions `swap_exact_tokens_for_tokens` and `swap_tokens_for_exact_tokens` will require a couple of changes to the AMM and Router pallets in order for them to work. Let's sync up tomorrow and discuss how this can be implemented.

**Comment by c02fee** [comment]
Sure, sounds like a plan , will push the branch which I am working, started to implement skeleton code, Thanks
@drbh

**Comment by c02fee** [comment]
* `sort_tokens` is it similar to the `sort_asset` ?
* `swap` function
* `safe_transfer_from` function
* `swap` for pair

**Comment by c02fee** [comment]
Implemented via :- https://github.com/parallel-finance/parallel/tree/feat/update-swaps-and-refactoring
