### ISSUE TITLE
AMM pool will be deleted accidently after one trade/removeLiquidity

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1188]

**Comment by Helen8** [comment]
1/20/22 - Unresolved, details here: https://parallelfi.slack.com/archives/C02Q394Q65A/p1642696920065500?thread_ts=1642657720.062700&cid=C02Q394Q65A

Steps to reproduce:
Step 1: Create Pool and verify exists.
Step 2: Add liquidity to pool (multiple users pref)
Step 3(Optional): Execute a  trade on the pool
Step 4: Remove piece of liquidity from pool for a single user
Step 5: See that pool has been deleted.

1/12/22 issue found - The [1000,100] pool using asset 9900 is gone. This was the pool the FE team was testing with
