### ISSUE TITLE
avoid AMM calculation overlow when tokens have big decimals

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1190]
We would like to avoid overflow due to big decimals

**Comment by Helen8** [comment]
@ashi20192020ayush What's the latest status on this? It's a high priority

**Comment by ashi20192020ayush** [comment]
@Helen8 I have done almost all the changes. However I am facing one issue `MaxEncodedLen` for FixedU128. I am working on to find a solution. I already reached out to @GopherJ if he has any idea.

**Comment by GopherJ** [comment]
I guess it's fixed
