### ISSUE TITLE
system.CallFiltered error when transferring assets on regnet

### ISSUE THREAD

**Issue by drbh** [parallel-finance/parallel#1279]
Users cannot transfer assets. When a user tries to transfer from one account to another they get a `system.CallFiltered` error.

See an example of Bob attempting to transfer KSM to Alice here:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fregnet-rpc.parallel.fi#/explorer/query/0xa8f0977279ff4d40959dea9e081e2c5727dc772c769ea943198cf758db0f84dc

**Comment by drbh** [comment]
@GopherJ any ideas why this is not allowed?

**Comment by GopherJ** [comment]
@drbh not yet. it looks weird
