### ISSUE TITLE
Unbond time has one era's delay

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1301]

**Comment by MrPai** [comment]
If we want to decrease this delay, the key problem is how to guarantee that our system has enough assets distributed to users.
 Since now there is one era's delay, then we probably can make sure `withdraw_unbond` has been invoked and the money success transfer from relaychain to parachain. but if we decrease this "waiting time", how can we guarantee this?
This could be the key problem we need to solve.

**Comment by MrPai** [comment]
consider add a storage record withdrawals amount in callback, before transfer money to users, check this amount first, if amount is enough,just make the transfer,if not which means withdraw-unbond is not finished or the asset is still locked on relaychain.

**Comment by GopherJ** [comment]
@MrPai if we call settlement before the relaychain's new era, will this problem still be there?

**Comment by MrPai** [comment]
if `x` is a fixed value or update each block, or update on each era? because when users unstake on parachain, `x` keep changing on relaychain.

**Comment by GopherJ** [comment]
@MrPai we can record the started blocknumber of current era. Then the unbond time will be:

```
started_blocknumber + bonding_duration
```

and Alice, Bob can withdraw at the same time

**Comment by MrPai** [comment]
If we store `started_blocknumber`,  we need to consider the frequency of updates about it.

and truly, how can we guarantee both `unbond` and `withdraw_unbond` is success.

**Comment by MrPai** [comment]
I think we need to consider updating some status in xcm-callback,
it's better for us to know the status of each period's operation, 
such as if period 1 is `withdraw_unbond `, before xcm sent, this operation's status could be **Pending**, and we can update it to **success** in xcm-callback, so we don't need to worry if the parachain really receive the money, if the operation is a success, it must be a success.

**Comment by MrPai** [comment]
Currently, we mint `staking_currency` in withdraw_unbonded xcm callback, but we do not know which period It corresponds to.
same as `unbond, bond_extra`, maybe period1‘s unbond operation is successed and period2's unbond is failed. however we don't know it now .

**Comment by MrPai** [comment]
See if we can solve this problem according to this solution:
https://github.com/parallel-finance/parallel/issues/1303#issuecomment-1041180744

**Comment by GopherJ** [comment]
## Storage

UnbondIndex => u32
UnstakeQueue => Map { unbond_index =>  }
UnbondInfo => Map { unbond_index => block_number }

**Comment by GopherJ** [comment]
https://github.com/parallel-finance/parallel/issues/1332#issuecomment-1043105157

**Comment by GopherJ** [comment]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/33961674/154843567-eb9491ed-e5b4-4d04-a440-ea6d80a0317d.png">
