### ISSUE TITLE
Upgrade heiko & parallel to v177

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1318]

**Comment by MrPai** [comment]
## Parallel Runtime Test
Refer to #1195

**Comment by MrPai** [comment]
## Initial network
1.1 Build docker config file
```
# use above config.yml, not use config.yml in repo
$ sudo parachain-launch generate config.yml
$ sudo docker-compose -f output/docker-compose.yml up -d --build

# shutdown the service
$ sudo docker-compose -f output/docker-compose.yml down
$ sudo docker volume prune -f
$ sudo docker network prune -f
$ sudo docker rmi -f $(sudo docker images | grep output | awk '{print $3}')
```
1.2 Parachain success produce blocks
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/26266313/156132873-0b045dc1-1bcb-4919-9e78-38165f195e85.png">

2.1 Upgrade parachain node to v0.9.17
change from parallelfinance/parallel:v1.7.6-rc4 to parallelfinance/parallel:v1.7.7-rc0, which means changed nodes from v0.9.16 to v0.9.17
```
$ nano output/parachain-2012.Dockerfile
>>> FROM parallelfinance/parallel:v1.7.7-rc0
```

2.2 upgrade collator node version
(one by one)
```
$ sudo docker-compose -f output/docker-compose.yml up -d --build parachain-2012-0
$ sudo docker-compose -f output/docker-compose.yml up -d --build parachain-2012-1
$ sudo docker-compose -f output/docker-compose.yml up -d --build parachain-2012-2
```

2.3 success update node to v1.7.7

**Comment by MrPai** [comment]
## Runtime upgrade
1.1 compile wasm-v1.7.7
Based on this [commit](https://github.com/parallel-finance/parallel/tree/f8fed4776cf2818490a577c64729444596c34be3)
```
sudo srtool build -p parallel-runtime
```

1.2 parachainSystem.authorizedUpgrade


1.3 parachainSystem.enactAuthorizedUpgrade

1.4 success

**Comment by MrPai** [comment]
## Heiko Runtime Test
Refer to #1094

**Comment by GopherJ** [comment]
1. parallel-dev worked

![Uploading image.png…]()
