### ISSUE TITLE
Design fast_unstake

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1331]
Option 1:
```
fn fast_unstake(liquid_amount: BalanceOf<T>, min_stake_amount: BalanceOf<T>)
```

fee should be around 0.6% + penalty 0.1%

**Comment by GopherJ** [comment]
1. instant
2. fee
3. capital

**Comment by GopherJ** [comment]
## Fast unstake using MatchingPool.total_stake_amount.free


## Fast unstake using MM

**Comment by GopherJ** [comment]
1. collateral sKSM
2. mint, collateral_asset, borrow => emode => borrow(100%)
3. pay to unstaker
4. wait 7 || 28
5. withdraw_unbonded
6. repay

**Comment by GopherJ** [comment]
## MM


## LS

**Comment by yrong** [comment]
yes, a little bit difficult to calc `repay_amount`. we may need some storage for( 
for whom in which block borrow how much DOT with DOT/U) and not mixed up with dot debt from other collaterals.  

maybe we can derivate a special borrower account from some tuple structure like (borrower,block,dot_u_asset_id,amount) which is unique and diffrent from normal account  and then `repay_amount` could be calculated with current `current_borrow_balance` without change
