### ISSUE TITLE
Add some statemine assets

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1360]
-  [ ] hrmp
-  [ ] add statemine asset

**Comment by yrong** [comment]
reproduce the issue you found when creating hrmp channel from statemine in my local setup, add an issue in cumulus [here](https://github.com/paritytech/cumulus/issues/1166) and will continue to find the cause

**Comment by yrong** [comment]
@GopherJ after removing the extra prefix the call could be executed in my setup but found another issue. The previous value of `requireWeightAtMost` in the example call seems not enough in polkadot-v0.9.18,  I just increase it from `1_000_000_000` to `2_000_000_000`

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/4383920/163087254-9ecf1b4f-b003-40c2-86fe-3ef2a7fd1b22.png">

**Comment by yrong** [comment]
calls to construct hrmp channel with steps as following:

1. initOpenChannel-from-heiko-to-statemine(proposal from heiko)
`0x1800010100020c0004000000000700e876481713000000000700e87648170006000300943577383c00e8030000e803000000900100`

2. initAcceptChannel-from-heiko-to-stamine&initOpenChannel-from-statemine-to-heiko(proposal from kusama in one step)

`0x1802080402006d6f646c70792f747273727900000000000000000000000000000000000000000070617261e80300000000000000000000000000000000000000000000000000000b0088e9962f09630001000100a10f0204060203009435779d011f0001010002140004000000000700e876481713000000000700e876481700060003009435775c1802083c01250800003c0025080000e803000000900100140d010004000101006d6f646c70792f74727372790000000000000000000000000000000000000000`

3. initAcceptChannel-from-statemine-to-heiko(proposal from heiko)
`0x1800010100020c0004000000000700e876481713000000000700e87648170006000300943577383c00e8030000e803000000900100`
