### ISSUE TITLE
ValidatorsMembership prefix migration

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1366]
https://github.com/paritytech/substrate/blob/master/frame/session/src/migrations/v1.rs#L62-L66

**Comment by MrPai** [comment]
Currently, we do not have any date under this membership, so I think there is nothing to migrate:
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/26266313/155942233-56255d1d-5ae4-450b-b125-a658c2919a06.png">

**Comment by GopherJ** [comment]
@MrPai shall we migrate the prefix? what I'm worried is that the liquidStakingAgents's pallet prefix in kv db is actually `ValidatorsMembership`

**Comment by MrPai** [comment]
I think there is no need to migrate it because members will be added under `LiquidStakingAgentsMembership`, and stored under prefix `LiquidStakingAgentsMembership`.

**Comment by GopherJ** [comment]
@MrPai ok I think it makes sense
