### ISSUE TITLE
Reduce parathread onboarding time

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1387]

**Comment by MrPai** [comment]
### 1.1 Here is the logic that `Onboarding` upgrade to `Parathread`:
https://github.com/paritytech/polkadot/blob/v0.9.17/runtime/parachains/src/paras/mod.rs#L1094-L1103

### 1.2 here you will find the key method is `on_new_session`:
https://github.com/paritytech/polkadot/blob/v0.9.17/runtime/parachains/src/initializer.rs#L258-L287

### 1.3 invoked by Seesion.SessionHandler
https://github.com/paritytech/polkadot/blob/v0.9.17/runtime/kusama/src/lib.rs#L362-L383

### 1.4 decrease the EpochDuration time would works:
https://github.com/paritytech/polkadot/blob/v0.9.17/runtime/kusama/src/lib.rs#L251-L263

**Comment by GopherJ** [comment]
@MrPai thanks I checked also 1.1, 1.2 and 1.3 this morning
