### ISSUE TITLE
Fix gift diff logic

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1403]

**Comment by rjman-ljm** [comment]
<img width="874" alt="image" src="https://user-images.githubusercontent.com/44558375/156530950-e34344a7-21f0-4870-a02a-e23d56a09284.png">
Vanilla: existential_deposit = 0.01 HKO

**Comment by rjman-ljm** [comment]
<img width="847" alt="image" src="https://user-images.githubusercontent.com/44558375/156536269-788ba4a0-daab-4d14-a909-d8cf3e47557e.png">
<img width="891" alt="image" src="https://user-images.githubusercontent.com/44558375/156541612-f8b41d0d-4943-4073-94bb-70f0bd325217.png">

**Comment by rjman-ljm** [comment]
@GopherJ 
vanilla has a constant `ExistentialDeposit = 0.01 HKO` causing that situation (HKO = 0.035), I did these change( [code](https://github.com/parallel-finance/parallel/pull/1400/files#diff-9a08c969144a056406ced2d9dde2f410e0135639d066f770d14b702ebf909a80R141)) to fix it.

**Comment by rjman-ljm** [comment]
It behaves as follows.
<img width="847" alt="image" src="https://user-images.githubusercontent.com/44558375/156536269-788ba4a0-daab-4d14-a909-d8cf3e47557e.png">

**Comment by rjman-ljm** [comment]
formula: `total_gift = existential + gift_amount`
if gift_amount set to 0.025 HKO, total_gift = [0, 0.035]
After the change, the amount of `total_gift` may increased from 0.025 to 0.035, we can reduce the `gift_mount` with 0.015HKO to keep it in a [0, 0.025].
