### ISSUE TITLE
LS relaychain & parachain's current_era, era_start_block monitoring

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1429]
A service is needed to monitor relaychain's current era & era start block and compare it with parachain's current state. If they didn't match then send an alert to channel

**Comment by GopherJ** [comment]
Relaychain: api.query.staking.currentEra
Parachain: api.query.liquidStaking.currentEra

**Comment by rjman-ljm** [comment]
done https://github.com/parallel-finance/parallel-monitor/blob/master/src/service/liquidStaking/index.ts
