### ISSUE TITLE
Avoid overwriting staking_ledger with old data

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1455]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fregnet2-rpc.parallel.fi#/explorer/query/3042 this is found in regnet2 and the reason for it to happen is that `update_staking_ledger` & `notification_received` happened at the same block, `update_staking_ledger` overwrite current staking ledger using old data

**Comment by GopherJ** [comment]
we have two ways for solving this:

- find a hack to verify data
- simulate rewards

**Comment by MrPai** [comment]
A suggestion about using `Merkletree` to solve this problem:
we can store Merkle root about relaychain, suppose store 100 Merkle root in a set, this 100 Merkle root should all be behind after the relaychain block that we invoke xcm bond/bond_extra.

So we can confirm that we use available relaychain Ledger.

**Comment by GopherJ** [comment]
## Simulate Rewards Tech Design


### Storage

EraPercentagYield => Rate  # default to 1.0001075425965438 * 1e18 in heiko and 1.0003590459824236 in parallel

### Call

update_era_percentage_yield

### Helper

do_accre_interests

**Comment by GopherJ** [comment]
## Version Management Tech Design

**Comment by GopherJ** [comment]
## Lock design

### Storage

HasUpdated => OrderedSet

**Comment by GopherJ** [comment]
At the same time, we should guarantee that stake-client to be executed at the middle of every era instead of approaching the next era
