### ISSUE TITLE
Loss of accuracy on accountCollateral

### ISSUE THREAD

**Issue by yubo-ruan** [parallel-finance/parallel#156]
**Description**

When user supply 1000 unit of assets, accountCollateral will become 999.99999999 instead of 1000. Is it a possible loss of accuracy of decimal? 

**Steps to Reproduce**

1. Go to a new test account
2. Click on supply with max
3. Go to see the supply balance 
4. See 999.99999999

**Expected vs. Actual Behavior**

We should expect 1000 deposit balance instead of 999.999999999

**Environment**

testnet.parallel.fi

**Logs, Errors or Screenshots**

![image](https://user-images.githubusercontent.com/40745291/119884614-b053c400-bee5-11eb-91f2-1b3d20162809.png)

**Comment by yubo-ruan** [comment]
@yz89 could you take a look at this

**Comment by MrPai** [comment]
I wonder if this will block the consensus since each node will figure out a few differences, not sure.

**Comment by GopherJ** [comment]
is this solved?  @yz89

**Comment by yubo-ruan** [comment]
front-end will only show 2 decimals. let's use the polkadot.js.org to check it

**Comment by yz89** [comment]
> is this solved? @yz89

Not yet.

**Comment by GopherJ** [comment]
I think we can still reproduce similar issue while borrowing:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/33961674/122162265-da295680-cea5-11eb-9967-d650d49336c4.png">

**Comment by GopherJ** [comment]
<img width="977" alt="image" src="https://user-images.githubusercontent.com/33961674/122162470-32f8ef00-cea6-11eb-9082-2b35155062d8.png">
