### ISSUE TITLE
Relaychain similar staking rewards distribution

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1652]

**Comment by MrPai** [comment]
Some suggestion:
- Add Storagemap, update when push Relaychain.Ledger 
`EraIndex => TotalRewards`

- Add function payout_stakers, 
Now the problem is how to distribute rewards to Users.

**Comment by MrPai** [comment]
Solution for distribute rewards to Users:
- 1.1 Add DoubleMap
   storing users' stake amount during this era
  `EraIndex => AccountId => amount`
- 1.2 Add StorageValue, historyDepth
   Just like relaychain, any era beyond "currentEra - historyDepth" will be remove, can not receive Rewards anymore
   `u32`
- 1.3 Add Storagemap, Total Insurance of sKSM
   `EraIndex => Corresponding Insurance of sKSM`

**Process**
- 2.1 get totalReward amount during this era
- 2.2 get total Insurance amount of sKSM
- 2.3 calculation
   `user_reward = (user_sKSM_balance - user_current_era_stake_amount)/ Corresponding_total_Insurance_of_sKSM`

**Comment by MrPai** [comment]
**Question**:
Suppose Alice stake 100 KSM on current era and mint 100 sKSM out, then directly transfer to Bob, even though Alice can not get the reward about this 100 sKSM, however Bob can.

**Solution**:
Consider storing a Ledger for each user on Parachain, just exactly like Relaychain does.
and when distributing reward, consider both sKSM's amount and users' Ledger data on parachain.

**Comment by MrPai** [comment]
https://www.notion.so/parallelfinance/Solution1-Token-Distributed-Model-5b458367d13045aaacd282da214f01dd
