### ISSUE TITLE
reward and slash repeaters

### ISSUE THREAD

**Issue by drbh** [parallel-finance/parallel#1656]
implement functions to reward and slash repeaters

- [ ] reward per submission amount
- [ ] reward - repeater for N submissions (extrinsic to call)
- [ ] slash - repeater for N submissions (extrinsic to call)
- [ ] slash for not participating

we need tests that are like
1. 10 repeaters sign up and all act good, all get rewards for 100 rounds
2. 10 repeaters sign up and 5 are good and 5 get slashed

**Comment by palletd** [comment]
https://github.com/paritytech/substrate/blob/master/frame/membership/src/lib.rs

**Comment by palletd** [comment]
https://github.com/open-web3-stack/open-runtime-module-library/tree/master/oracle
