### ISSUE TITLE
rethink on matching moment

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1736]

**Comment by GopherJ** [comment]
from my calculation it should be:

Parallel: eraStartBlock + 12600
Heiko: eraStartBlock + 3150

**Comment by GopherJ** [comment]
Also we can also introduce session, we can have 24 sessions

at session 21 we do matching

**Comment by MrPai** [comment]
| Era | Session | Trigger | Relaychain | Parachain |
| :------: | :------: | ------ | ------ | ------ |
| 1 | 1 | - |  - |  - | 
| 1 | 2 | - |  - |  - |
| 1 | 3 | - |  - |  - |
| 1 | 4 | - |  - |  - |
| 1 | 5 | - |  - |  - |
| 1 | 6 | - |  update_solution |  - |
| 2 | 1 | new_session/trigger_new_era |  increase current_era |  - | 
| 2 | 1 | end_session/end_era |  calculate reward/EraPaid |  - | 
| 2 | 1 | start_session/start_era |  increase active_era |  - | 
| 2 | 2 | - |  - |  - |
| 2 | 3 | - |  - |  - |
| 2 | 4 | - |  - |  - |
| 2 | 5 | - |  - |  - |
| 2 | 6 | - |  - |  - |
