### ISSUE TITLE
add pallet-scheduler to achive forkless runtime upgrade

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#175]
this is more for vanilla

**Comment by GopherJ** [comment]
not sure how to do this for parachain...

**Comment by ayushmishra2005** [comment]
@GopherJ Is this for adding `pallet-scheduler` in runtime?

**Comment by GopherJ** [comment]
@ayushmishra2005 yes, we need to understand how to do forkless upgrade at a specific block number.

I'm not sure yet how to do this for parachain

**Comment by GopherJ** [comment]
parachain can upgrade using:

<img width="916" alt="image" src="https://user-images.githubusercontent.com/33961674/120769715-f812c500-c54f-11eb-805d-1f0cbbee31f6.png">
