### ISSUE TITLE
Cancel unstake improvement

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1772]
currently it supports only cancel at the same era. We should support cancel at any era

**Comment by MrPai** [comment]
Seems like in `cancel_unstake`, we can easily convert the DOT amount stored in `Unlockings` into sDOT amount, and directly add it to `matchingpool.total_stake_amount.free`. the steps are following:
- 1. decrease DOT amount in `Unlockings`, just like what `rebond` does.
- 2. calculate sDOT amount according to the current exchange rate, and mint to users
- 3. add DOT amount to `matchingpool.total_stake_amount.free`.
It's all that we should do in `cancel_unstake`. did I miss anything?

**Comment by MrPai** [comment]
## Option2: User rebond directly via XCM
1. In Era 1, Alice stake 50, Bob stake 50, matching result is bond 100 on relaychain
2. In Era 2, Alice stake 100, Bob unstake 50, matching result is bond 50 on relaychain
3. In Era 3, Bob wants to cancel_unstake 50, if Bob can rebond directly on relaychain, there is no unlocking chunks on relaychain.
