### ISSUE TITLE
Test Ledger Parallel on Ledger Live (dev mode)

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#1824]
refer #1819

**Comment by MrPai** [comment]
## Prepare:
### 1 turn on dev mode
![image](https://user-images.githubusercontent.com/26266313/178922859-647f4d37-6c8b-4034-8e65-50bd0327c924.png)

### 2 install legder app
![image](https://user-images.githubusercontent.com/26266313/178922902-ef7fd1b4-7afc-428a-898a-196fa24c163f.png)

**Comment by MrPai** [comment]
## Test Cases

**Comment by MrPai** [comment]
Decimal issues about token:
### 1 xtoken.transfer
<img width="476" alt="image" src="https://user-images.githubusercontent.com/26266313/179692919-5fcfa20c-e27e-48ca-b492-0c34486f0527.png">
<img width="472" alt="image" src="https://user-images.githubusercontent.com/26266313/179692990-6d423e56-180e-4b94-b437-3084b237e808.png">
<img width="434" alt="image" src="https://user-images.githubusercontent.com/26266313/179693051-228e6486-47af-4754-be9e-38a31038ee42.png">
it's should be 0.1 DOT, let's show it "1000000000" without unit.

**Comment by MrPai** [comment]
Test Ledger on Parallel DAPP
Test Portal: https://app.parallel.fi/#/overview
Endpoint: wss://rpc.parallel.fi

**Comment by MrPai** [comment]
### 1 stake without supply staked DOT to Money Market
<img width="854" alt="image" src="https://user-images.githubusercontent.com/26266313/179710765-2a468315-c7a1-4468-b040-641719e65054.png">

<img width="541" alt="image" src="https://user-images.githubusercontent.com/26266313/179710559-b3974228-a152-4709-9fb0-c4a04a93c940.png">

### 2 stake and supply staked DOT to Money Market
<img width="879" alt="image" src="https://user-images.githubusercontent.com/26266313/179710956-0a38ff91-ff15-470f-ac24-8dd09a2c07b7.png">
<img width="594" alt="image" src="https://user-images.githubusercontent.com/26266313/179711070-0e822a5b-570b-46a2-b5d4-116058de2181.png">

**Comment by MrPai** [comment]
Pallets need to enable nesting:
- LiquidStaking, https://github.com/parallel-finance/parallel/tree/master/pallets/liquid-staking
- Loans, https://github.com/parallel-finance/parallel/tree/master/pallets/loans

**Comment by DRatParallel** [comment]
FYI team I've added a new user guide to the Parallel gitbook here: https://parallelfi.gitbook.io/parallel-finance/polkadot-network/parallel-x-ledger-hardware-wallet
