### ISSUE TITLE
One click sDOT/DOT LP

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1858]

**Comment by alannotnerd** [comment]
![image](https://user-images.githubusercontent.com/24879490/188359353-4ded08cb-6412-4004-8f13-ed3de704e290.png)

Simulation: 
https://docs.google.com/spreadsheets/d/1WoGpeKkRQQoLVhEbVXIii4eBF1UgcKNQdBcbMFU6pdg/edit?usp=sharing
