### ISSUE TITLE
 highly out of sync

### ISSUE THREAD

**Issue by zmyya** [parallel-finance/parallel#1910]
Restarting the docker service node will synchronize to the latest height, and then it will not be synchronized

logs
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/37679261/205843442-2b264fd8-3df0-4850-806e-d5654ad9dfec.png">

config  --chain=parallel --ws-port=9944 --ws-external --rpc-external --rpc-cors=all --execution=wasm --ws-max-connections=2000

**Comment by zmyya** [comment]
thanks. i will try

**Comment by MrPai** [comment]
@zmyya  do you still have questions about this issue, if not, we are ready to close it.
