### ISSUE TITLE
Full Node does not connect to peers.

### ISSUE THREAD

**Issue by travnado300** [parallel-finance/parallel#1972]
Full node will not connect to parachain peers. Relay chain continues to be able to connect and seemingly maintain normal functionality. Node had been running for ~4 months seamlessly until 3 days ago it needed to be restarted and has not been able to reconnect to peers.

System has been restarted, network and firewall settings have been altered, to no avail. 

Verified by starting from a brand new database, different network, different device, using systemd, using docker, resetting full-node.sh script, and all yield the exact same result of connecting to relay chain peers but not parachain peers.

**Comment by SixoneKui** [comment]
I am experiencing the same issue.

**Comment by dcolley** [comment]
I can't reach any official boot nodes:
https://github.com/parallel-finance/specs/blob/55e3bac2f413ca0a44227b7c6b5c4c4ae0019b4e/parallel.json
```json
"bootNodes": [
    "/dns/bootnode-1.parallel.fi/tcp/30333/p2p/12D3KooWA3ngBk5UuAvtvANXRJSTjdCT9bz7AcdBqmnR64m3tRWb",
    "/dns/bootnode-5.parallel.fi/tcp/30333/p2p/12D3KooWGxnMnE1AFriohESDGQnpYBzbxBpRDf3MFNu8yuobJBbF"
  ],
```
Anyone else have the same problem, please try adding my node as follows:
```
--boot-nodes /dns/boot.metaspan.io/tcp/16092/p2p/12D3KooWAWknffkU5uJPYSNcJrwh5GN1ofWhFCUUY5uDTaB4yLAN
```

**Comment by travnado300** [comment]
Thank you @dcolley for resolving the issue. Issue resolved using this bootnode in chain specs and compiling from source. Devs should consider:

A) Verify security and sustainability of @dcolley private bootnode and update chain specs to include it in official bootnodes.
B) Determine issue with current official bootnodes and restart.

Leaving issue open until devs provide update for resolution.

**Comment by SixoneKui** [comment]
> Thank you @dcolley for resolving the issue. Issue resolved using this bootnode in chain specs and compiling from source. Devs should consider:
> 
> A) Verify security and sustainability of @dcolley private bootnode and update chain specs to include it in official bootnodes. B) Determine issue with current official bootnodes and restart.
> 
> Leaving issue open until devs provide update for resolution.

I tried to run with:
sudo docker run -it --privileged=true -v  /XXXXX:/parallel/data   parallelfinance/parallel:latest --base-path=/parallel/data   --chain=parallel --bootnodes="/dns/boot.metaspan.io/tcp/16092/p2p/12D3KooWAWknffkU5uJPYSNcJrwh5GN1ofWhFCUUY5uDTaB4yLAN"  --name=XXXX --rpc-cors all --rpc-external --ws-port=9944 --ws-external  

It seems the node is  still not syncing .

Do I use it the right way.

Many thanks

**Comment by nfekunprdtiunnkge** [comment]
I also tried using bootnodes @dcolley provided. Sometimes I get a peer or even two peers (without bootnodes param it is always at 0) but doesn't seem to be syncing.

**Comment by dcolley** [comment]
My existing node is able to stop & start, and obtains ±10 peers.

However, when I start a new node it won't sync.
I wonder if there is an issue with early blocks?

```bash
./parallel --chain parallel \
  --tmp \
  --database paritydb \
  -lsync=debug \
  --no-private-ip --no-mdns \
  --collator \
  --no-prometheus \
  --no-telemetry \
  --bootnodes /dns/boot.metaspan.io/tcp/16092/p2p/12D3KooWAWknffkU5uJPYSNcJrwh5GN1ofWhFCUUY5uDTaB4yLAN \
  --bootnodes /dns/boot.gatotech.network/tcp/33152/p2p/12D3KooWFnXeatXN73ytjDfcUNsoyRxLLK3tqmmzEjhbLhoGCDKt \
  --listen-addr /ip4/0.0.0.0/tcp/30339 \
  --public-addr /ip4/195.144.22.130/tcp/16095 \
  --relay-chain-rpc-urls ws://192.168.nn.nn:13015 # this is my internal polkadot rpc node
```

This log might be useful:
```
2024-05-08 16:55:07.600 DEBUG tokio-runtime-worker sync::import-queue: [Parachain] Error importing block 1: 0x51c5ee0668b3c2aa257ccf19f4e48ba8d854a45e59f654761621550bcbb5ec12: Import failed: Runtime Ethereum block not found, rejecting!
```

**Comment by dcolley** [comment]
testing with parallel-v1.9.7 syncing starts, v2.0.2 does not sync

**Comment by SixoneKui** [comment]
> My existing node is able to stop & start, and obtains ±10 peers.
> 
> However, when I start a new node it won't sync. I wonder if there is an issue with early blocks?
> 
> ```shell
> ./parallel --chain parallel \
>   --tmp \
>   --database paritydb \
>   -lsync=debug \
>   --no-private-ip --no-mdns \
>   --collator \
>   --no-prometheus \
>   --no-telemetry \
>   --bootnodes /dns/boot.metaspan.io/tcp/16092/p2p/12D3KooWAWknffkU5uJPYSNcJrwh5GN1ofWhFCUUY5uDTaB4yLAN \
>   --bootnodes /dns/boot.gatotech.network/tcp/33152/p2p/12D3KooWFnXeatXN73ytjDfcUNsoyRxLLK3tqmmzEjhbLhoGCDKt \
>   --listen-addr /ip4/0.0.0.0/tcp/30339 \
>   --public-addr /ip4/195.144.22.130/tcp/16095 \
>   --relay-chain-rpc-urls ws://192.168.nn.nn:13015 # this is my internal polkadot rpc node
> ```
> 
> This log might be useful:
> 
> ```
> 2024-05-08 16:55:07.600 DEBUG tokio-runtime-worker sync::import-queue: [Parachain] Error importing block 1: 0x51c5ee0668b3c2aa257ccf19f4e48ba8d854a45e59f654761621550bcbb5ec12: Import failed: Runtime Ethereum block not found, rejecting!
> ```
> 
> Could be related to : [polkadot-evm/frontier#223](https://github.com/polkadot-evm/frontier/issues/223)



I have a node that was synced before, but lost sync a few days ago
Then I restart this node several times, but still cannot sync, (0 peers problem occurs)

**Comment by nfekunprdtiunnkge** [comment]
Using both bootnodes I was able to sync again, thanks!

```
--bootnodes /dns/boot.metaspan.io/tcp/16092/p2p/12D3KooWAWknffkU5uJPYSNcJrwh5GN1ofWhFCUUY5uDTaB4yLAN 
 --bootnodes /dns/boot.gatotech.network/tcp/33152/p2p/12D3KooWFnXeatXN73ytjDfcUNsoyRxLLK3tqmmzEjhbLhoGCDKt 
 ```

**Comment by dcolley** [comment]
> Using both bootnodes I was able to sync again, thanks!
> 
> ```
> --bootnodes /dns/boot.metaspan.io/tcp/16092/p2p/12D3KooWAWknffkU5uJPYSNcJrwh5GN1ofWhFCUUY5uDTaB4yLAN 
> --bootnodes /dns/boot.gatotech.network/tcp/33152/p2p/12D3KooWFnXeatXN73ytjDfcUNsoyRxLLK3tqmmzEjhbLhoGCDKt 
> ```

What version client are you using?

**Comment by wangminqi** [comment]
> > Using both bootnodes I was able to sync again, thanks!
> > ```
> > --bootnodes /dns/boot.metaspan.io/tcp/16092/p2p/12D3KooWAWknffkU5uJPYSNcJrwh5GN1ofWhFCUUY5uDTaB4yLAN 
> > --bootnodes /dns/boot.gatotech.network/tcp/33152/p2p/12D3KooWFnXeatXN73ytjDfcUNsoyRxLLK3tqmmzEjhbLhoGCDKt 
> > ```
> 
> What version client are you using?

I did not try 2.0.2, but I think anything above >2.0.2 works.

**Comment by nfekunprdtiunnkge** [comment]
> > Using both bootnodes I was able to sync again, thanks!
> > ```
> > --bootnodes /dns/boot.metaspan.io/tcp/16092/p2p/12D3KooWAWknffkU5uJPYSNcJrwh5GN1ofWhFCUUY5uDTaB4yLAN 
> > --bootnodes /dns/boot.gatotech.network/tcp/33152/p2p/12D3KooWFnXeatXN73ytjDfcUNsoyRxLLK3tqmmzEjhbLhoGCDKt 
> > ```
> 
> What version client are you using?

Latest one 2.0.6

**Comment by 0xrjman** [comment]
https://telemetry.polkadot.io/#/0xe61a41c53f5dcd0beb09df93b34402aada44cb05117b71059cce40a2723a4e97

🙏 Thanks, everyone! The downtime earlier was due to a disk space issue, our bootnodes is up and running again.

**Comment by SixoneKui** [comment]
> https://telemetry.polkadot.io/#/0xe61a41c53f5dcd0beb09df93b34402aada44cb05117b71059cce40a2723a4e97
> 
> 🙏 Thanks, everyone! The downtime earlier was due to a disk space issue, our bootnodes is up and running again. If you still encounter the same issue, feel free to raise it again.

Hi,

I tried 2.0.6 without specifying the bootnodes. I still cannot sync.
Please take a look.

Many thanks
