### ISSUE TITLE
Curve rate model support

### ISSUE THREAD

**Issue by yz89** [parallel-finance/parallel#227]
**Motivation**

We plan to implement the Curve Interest Rate Model as the design in the [white paper](https://docs.parallel.fi/white-paper#3-experimental-models). Although it is experimental in nature, it is conducive to our understanding and exploration of interest rate models.

**Suggested Solution**

First, we need to find a suitable polynomial that combines a power function and an exponential function. And then define the smallest representation of this polynomial.

**Additional Information**

#226 has refactored the rate model to support the curve model.

**Comment by yz89** [comment]
Hi @c410-f3r, Could you do some research about this?

**Comment by GopherJ** [comment]
I'm a little bit worried on the block producing time. Hope the calculation is fast enough

> And then define the smallest representation of this polynomial.

this is important

**Comment by yubo-ruan** [comment]
Hey guys, here is how I think about this issue. 

https://github.com/parallel-finance/parallel/issues/229


I noticed that @yz89 change to Jump_rate and jump_utilization. Good direction.
