### ISSUE TITLE
Modify the Interest Rate Curve and Add Interest Bearing Token

### ISSUE THREAD

**Issue by yubo-ruan** [parallel-finance/parallel#229]
**Quick Issue**
We use the exact same interest rate model parameters from Compound chain. I think we should change it as soon as possible. 

**Suggested Solution**

1. Change name to 
base_rate: Rate
max_rate: Rate
optimal_rate: Rate
optimal_utilization: Ratio

**New Curve Motivation**

Currently, we are using the classic piecewise linear function from the Compound interest rate model. However, it is not optimized for KSM pool because of the KSM staking rewards. I will explain why in the next two paragraphs. 

Notice, staking rewards will compete with KSM lending pool. If the KSM staking rate is higher than the lending rate, users have the incentive to withdraw and stake. If staking rate is lower, users have the incentive to unstake and supply to KSM pool.

Since we will have leverage staking functionality, as long as the borrowing rate is lower than the staking rate, users have an incentive to borrow and leverage up.  Similarly, as long as the lending rate is higher than the staking rate, users have an incentive to lend in our lending poo. In the end, the equilibrium will be reached when the borrowing rate is higher than the staking rate (no one wants to borrow), and the lending rate is lower than the staking rate (no one want to supply). 

2. Peg the optimal_rate to the staking_apy (currently 14%)

Based on the above reasons, we should put optimal_rate in the middle of supply_rate and borrow_rate
optimal_rate = staking_apy + interest_rate_distance/2
interest_rate_distance = borrow_rate - supply_rate = borrow_rate * [1 - utilization * (1- reserveRatio)]
Therefore: 
optimal_rate = staking_apy +  borrow_rate * [1 - utilization * (1- reserveRatio)] / 2

Now the question is how to calculate the dynamic staking rate. I suggest using 14% to get started but we should peg to actual staking apy. 

staking_apy = xKSM_exchange_rate / xKSM_exchange_rate(last_week) * 52.1429 

**Alternatives**

We can use the exponential curve that is on our white paper, but it is not the highest priority and we should do more research before we use it. 

**Interest-bearing Token Motivation**

Compatibility is one of the most important factors that make DeFi scale and grows. We should make our money market be one of the financial primitives for our users. We want to add interest-bearing tokens to our users. 

Potently use case includes supplying our interest bearing token to AMM or yield aggregator. (check out https://curve.fi/aave)

**Suggested Solution**

After supplying to our lending pool, users should receive the interest-bearing token. I suggest we use the name hToken for Heiko network and pToken for Parallel network. For example, after users supply xDOT, they should receive pxDOT based on the exchange rate (totalCash + totalBorrow - totalReserve) / totalSupply 

This token should be transferrable and composable to other applications in our Parachain and potentially in other parachain. 

**Alternatives**

No certificate token issued, less composability for our ecosystem. 

**Question**

Should we use xToken module for interest-bearing token or another library?

**Comment by yz89** [comment]
Check #226, it has been changed to jump_rate or jump_utilization.

**Comment by yubo-ruan** [comment]
Compound ethereum contract uses JumpRate model. Using jump_rate or jump_utilization still gives an impression of Compound's shadow. 

![image](https://user-images.githubusercontent.com/40745291/122696775-be50e800-d1f8-11eb-8a3a-f229bf8b2e07.png)

**Comment by c410-f3r** [comment]
> We can use the exponential curve that is on our white paper, but it is not the highest priority and we should do more research before we use it.

Looks like #222 will be postponed.

Should the new curve replace `InterestRateModel::Jump` or, at least initially, is it better to add yet another variant?
```rust
pub enum InterestRateModel {
  Curve(CurveModel),
  Jump(JumpModel),
  Optimal(OptimalModel),
}

**Comment by yz89** [comment]
Move the design to notion. https://www.notion.so/parallelfinance/Modify-the-Interest-Rate-Curve-and-Add-Interest-Bearing-Token-8e6498aedbf4488585c20256a8062546
