### ISSUE TITLE
check on-chain staking's missing parts

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#232]
- [x] amount to stake, unstake
- [x] Exchange Rate
- [x] leverage staking
- [x] Staking APY
- [x] Total Stakers
- [x] xKSM Market Cap
- [x] Bonded Ratio (not sure to understand)
- [x] Staking Fee
- [x] Pending Unstake
- [x] Validator Sets
- [x] Delivery date

<img width="671" alt="image" src="https://user-images.githubusercontent.com/33961674/122855363-b94e7e80-d347-11eb-92e5-8166f747f54c.png">

**Comment by MrPai** [comment]
leverage staking can work, after we get xKSM from LiquidStaking Pallet by stake(), we could use it as collateral in the Loans pallet.

**Comment by GopherJ** [comment]
do you think if it's ok to calculate `validator set` in frontend? or do we prefer to do it in off-chain

**Comment by MrPai** [comment]
> do you think if it's ok to calculate `validator set` in frontend? or do we prefer to do it in off-chain

I think off-chain will be better for now

**Comment by MrPai** [comment]
here is the frontend API for reference: https://www.notion.so/parallelfinance/check-on-chain-staking-s-missing-parts-998ba8e4ee5e49078ccf94d38fab4726
@crystalynliu
