### ISSUE TITLE
Governance money markets

### ISSUE THREAD

**Issue by yz89** [parallel-finance/parallel#248]
**Motivation**

The money markets should be able to be regulated. We lack methods such as `add_market`, `active_market`, `update_market`, `supervise_market`, etc. Before adding these dispatchables, we need to do some refactoring, such as extracting some storage into a Market Struct. 

**Suggested Solution**

- Define the market struct in a new market.rs file with such fields:
```
Market {
  intereste_model    InterestModel
  collateral_factor    Ratio
  reseve_factor    Ratio
  close_factort    Ratio
  liquidate_incentive    Rate
  state(enum):
  - pending
  - active
  - supervision
}
```
- Define Markets StorageMap to store each money market. StorageMap: CurrencyId -> Market.
- Replace the old storage `CloseFactor`, `LiquidationIncentive`, `ReserveFactor`, `CollateralFactor`, `CurrencyInterestModel`, `Currencies` by using the new Markets.
- Implement the `add_market` call to allow the community to add a new market. The state of a new market should be pending.
- Implement an `active_market` call to allow the community to active the pending market, which means the pending market can be opened to the users actually. The state of the pending market should be updated to active.
- Implement the `update_market` call to allow the community to update market details includes interest_model, collateral_factor, etc. Remove the `set_rate_model`, `set_liquidation_incentive`.
- we can discuss more the supervise_market call.

**Additional Information**

I'm not sure how many effects will have after the refactor, please assess the change momentum before you start. This is going to be a big change, so divide the work up into multiple PRs.

**Comment by GopherJ** [comment]
missing parts:

- add_market
- active_market
- update_market

remove:
- set_liquidation_incentive
- set_rate_model
