### ISSUE TITLE
Lack of bounds checking

### ISSUE THREAD

**Issue by yz89** [parallel-finance/parallel#257]
`mint_amount` has no boundary limit, it is recommended to enhance.

What range do you think the boundary should be? @kaichaosun @GopherJ

**Comment by kaichaosun** [comment]
After think about a reasonable number for a while, we actually don't need this range.
Like, we support user with 0,001 ksm and 100_000 ksm, to give it a boundary limit and let user make multiple calls doesn't make much sense.

**Comment by yz89** [comment]
I agree with you. We hardly find a reasonable number that suits each money market with different decimals. 

I think we can move up the transfer action:
```
T::Currency::transfer(currency_id, &who, &Self::account_id(), mint_amount)?;
```
Let the user meet `InsufficentBalance` first rather than `Overflow`.
