### ISSUE TITLE
Fix benchmarks

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#267]
benchmarks are broken recently due to:

- loans benchmarks only use DOT but in vanilla we use KSM, which fails on `enable_currency` check
- liquidate_borrow has changed
- liquid-staking's reserve factor? not sure

**Comment by yz89** [comment]
loans benchmarks mocked its own Runtime, no matter with vanilla.

**Comment by GopherJ** [comment]
@yz89  I feel it's not the case because if I change `DOT` to `KSM` part of pbs are fixed
