### ISSUE TITLE
Liquid-staking1.0 summary

### ISSUE THREAD

**Issue by yz89** [parallel-finance/parallel#290]
**Motivation**

We complete the basic requirement for liquid-staking. But there is still a long way to the product ready. We need to summarize the improvements and bugs of liquid-staking 1.0.

Feel free to schedule a meeting to discuss them.

**Comment by MrPai** [comment]
https://www.notion.so/parallelfinance/Staking1-0-Summary-20d73e6b8efa4c88a0a726b4a652c5e1
