### ISSUE TITLE
New AMM Curve

### ISSUE THREAD

**Issue by yubo-ruan** [parallel-finance/parallel#308]
@c410-f3r

**Comment by yubo-ruan** [comment]
**Feedback** 

1. Can the left portion of the curve be more like a constant product curve? We'd like to make the price change significantly otherwise it is easy for one user to swap all of the pool
2. Can the const sum portion be more located in the middle of the curve similar to the second chart? In this way, we can have a more balanced xDOT, DOT amount at the constant sum portion.


**Screen**


![unknown.png](https://images.zenhubusercontent.com/60ea1e7ee995490426a0915c/ae59ad06-8d73-4a48-ab5d-b8b3563565d0)

**Comment by yz89** [comment]
Close the issue for now. We'll talk about that when we actually going to implement the insurance pool and stability pool.
