### ISSUE TITLE
parallel-subql 

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#312]

**Comment by GopherJ** [comment]
example: 

- https://github.com/bifrost-finance/bifrost-subql
- https://github.com/AcalaNetwork/acala-subql

**Comment by GopherJ** [comment]
hi @ashi20192020  any progress or blocker on this?

**Comment by ashi20192020ayush** [comment]
Deployed https://explorer.subquery.network/subquery/parallel-finance/parallel-finance
