### ISSUE TITLE
Refactor code in loans pallet, mainly storages and dispatchables

### ISSUE THREAD

**Issue by kaichaosun** [parallel-finance/parallel#32]
Items needed to be refactored includes,
- comments/rustdocs for all errors/events, dispatchables, storages
- minimum storage usage, bounded execution/storage, short function
- add traits for pallet to abstract the behaviour
- move the main pallet implementation in lib.rs
- extract to new pallets if storages/dispatchables can be separated
- exchange_rate to use fixed point number, rational of precision
- pub mod module change to pallet, put impl Pallet out of this module
- license

**Comment by yz89** [comment]
comments/rustdocs for all errors/events, dispatchables, storages
