### ISSUE TITLE
Make xcm token transfer work from parachain to relay chain

### ISSUE THREAD

**Issue by kaichaosun** [parallel-finance/parallel#33]
The transferred token to parachain should work in loans pallets.

**Comment by GopherJ** [comment]
https://github.com/encointer/pallets/blob/pallet-xc-transfer-rococo/xc-transfer/src/lib.rs#L122-L140

**Comment by GopherJ** [comment]
https://github.com/paritytech/polkadot/issues/2564

**Comment by GopherJ** [comment]
https://github.com/paritytech/polkadot/issues/2547

**Comment by GopherJ** [comment]
https://github.com/Phala-Network/phala-blockchain/blob/3fbd63f23088e3d4fe41db01342d1303d36f44a8/scripts/js/sendXcm.js#L9-L62

**Comment by GopherJ** [comment]
looks like will be solved: https://github.com/paritytech/polkadot/issues/2564#issuecomment-839724678

**Comment by GopherJ** [comment]
https://github.com/Phala-Network/phala-blockchain/pull/139/files

**Comment by GopherJ** [comment]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/33961674/120329326-5193ad80-c31e-11eb-8378-952e6595b0c1.png">

doesn't work as well

**Comment by GopherJ** [comment]
I just tried:

<img width="591" alt="image" src="https://user-images.githubusercontent.com/33961674/121848384-8a6b5380-cd1c-11eb-855c-2b7abd491de5.png">

it works now
