### ISSUE TITLE
Benchmarking for built-in pallets

### ISSUE THREAD

**Issue by alannotnerd** [parallel-finance/parallel#352]
**Motivation**

To add weights for built-in pallets #346， we need to run benchmarking for each pallet on our own host. 

**Suggested Solution**

- [x] Add pallet's benchmarks in runtime
- [x] Run benchmark to generate weights file
- [x] Replace mock type with actual weight info.

**Comment by GopherJ** [comment]
@alannotnerd you can also try to run benchmarks in docker which can be easier as you dont need to copy the binary to a server
