### ISSUE TITLE
Implement LiquidStaking2.0, stake and unstake part

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#353]
**Motivation**

Planning to implement the liquidStaking2.0 code, include two pallets, and develop the stake&unstake logic first.
Here is the link to the design:
https://www.notion.so/parallelfinance/Staking-2-0-Design-32abf66bbd6c4100a3980928ca7fe850

The main method and storage design can be found here:
https://www.notion.so/parallelfinance/Design-data-structure-methods2-fbfe610f3425405fad06dba7cf0f604a

**Suggested Solution**

- [x] Initial LiquidStaking pallet
- [x] stake call 
- [x] unstake call
- [x] claim call
- [x] add matching pool storage
- [x] deposit_event_to_relaychain (matching logic)
- [x] add matching queue storage, for all single user

**Comment by MrPai** [comment]
Initial a draft PR about the pallet, #362

**Comment by MrPai** [comment]
## Context
Currently, for the `claim` method, users can claim token/xToken that they could without any other parameters.
Keep in mind that for a single user, he may stake/unstake in many eras, and for each era, the era's operation may be bond or unbond. 
Since we have a matching mechanism, so users may get part of their token directly while the other part need to wait a period.
Now, we have implemented the `claim` method to deal with all the above details, however, this makes the code complexity.

- For users' stake operation, who stake KSM and get xKSM back, the user needs to wait for at least 1 era to get xKSM back.
- For users' unstake operation, who unstake xKSM and get KSM back, the user needs to wait for at least 28 eras to get KSM back.

## Example
Suppose the exchange rate always to be 1.
### total_stake_amount > total_unstake_amount
1. in era 1, Alice stake 10 KSM, and Bob unstake 3 xKSM, 
total_stake_amount = 10, total_unstake_amount = 3, 
2. now era 1 ends, the matching mechanism takes effect, because total_stake_amount > total_unstake_amount, we need to **bond** 7 KSM on relaychain.
3. after matching, Bob can get 3 KSM back directly, while Alice can only get 3 xKSM directly, and the other 7 xKSM need to wait. the waiting time is 1 era because Alice's operation is stake.
4. now start in era 2, Alice can get the left 7xKSM back. this should be done while Alice calls the `claim` method.

### total_stake_amount < total_unstake_amount
5. in era 2, Alice stake 11 KSM, and Bob unstake 13 xKSM,
total_stake_amount = 11, total_unstake_amount = 13, 
6. now era 2 ends, the matching mechanism takes effect, because total_stake_amount < total_unstake_amount, we need to **unbond** 2 KSM on relaychain.
7. after matching, Alice can get 11 xKSM back directly, while Bob can only get 11 KSM directly, and the other 2 KSM need to wait. the waiting time is 28 era because Bob's operation is unstake.
Bob can only claim his 2 KSM until era is 2+28=30.
8. now start in era 3, 

## Concern
As we know from the above example, many users may have many operations in different era, and the era may execute bond or unbond on relaychain.
even a user who stake can get xKSM back only after one era, but what if this user forget to claim it,  our system still need to store this user's record.
and what if a user has stake and unstake in one era?

## Solution
Currently, we have already implemented the `claim` method to handle this, Iterate the era index by accountId, and calculate the amount that can be claimed between instant part and delay part. 
however, the logic in current `claim` method is complexity.

we may improve it if we can invoke this method with some parameters, like era_index. so no need to iterate it in our logic.
but if we choose this way, it may change the user's experience. so we need to confirm with the production side.

**Comment by MrPai** [comment]
## New Design
According to the current solution, after our discussion, we may change some designs in the current solution.
### Stake
- Mint xToken instantly while user stake,
- record the total_stake_amount when user stake, do not record for a single user
- still need to match by era, which means now only use total_stake_amount for the matching mechanism
- do not consider the potential bug about exchangerate
- no need to claim for user's stake operation

### Unstake
- record total_unstake_amount, also record unstake amount for a single user (record era index too)
- store previous exchangrate, which means store 3 records about exchangerate,
- when user unstake, do not use the current exchangerate to calculate, use third from last
- user need to claim for their asset.
### Claim
-frontend need to invoke this method with era index, which means the user need to claim their asset one by one.

**Comment by MrPai** [comment]
For me personally, I prefer to use the current solution, `claim` method with no parameters, iterate the era index internally. need to add more unit tests and improve them.
please make some comments if have a better suggestion.

**Comment by yz89** [comment]
> we may improve it if we can invoke this method with some parameters, like era_index. so no need to iterate it in our logic.
but if we choose this way, it may change the user's experience. so we need to confirm with the production side.

We didn't change the user's experience, for this is the product design at this moment. There should be an unstake list for each user and a claim button for each line.

**Comment by Helen8** [comment]
1. On the front end design, we will need to add the claim button and confirm process. We did not add previously because we thought the unbond amount can automatically be returned to the user.
2. If the user can only unlock partial amounts at different eras, then yes we will also need to update the FE to show this. Right now, we assumed that the full amount will be unlocked at the same time.
3. Will the users know the transaction fee in KSM in advance for each claim?

**Comment by MrPai** [comment]
> 1. Aside from the use cases written above, there's another flow to consider where user stakes > gets xKSM > supply OR use as collateral to borrow - in QA and testing, we need to make sure those get tested and the correct xKSM amounts for unstake is accurate.
> 2. On the front end design, we will need to add the claim button and confirm process. We did not add previously because we thought the unbond amount can automatically be returned to the user.
> 3. If the user can only unlock partial amounts at different eras, then yes we will also need to update the FE to show this. Right now, we assumed that the full amount will be unlocked at the same time.
> 4. Will the users know the transaction fee in KSM in advance for each claim?
> 5. Note: If we add the rebond feature, this will add complexity.

1. there will be no problem with the amounts because xKSM is always mint according to `exchangrate`, the key factor is when xKSM use as collateral, its price should be stable.
2. we need claim button, think of that for a single user who unstake in different era, this user may have a serval `claim button` for each era.
3. yes, please update it in FE.
4. the fee can be calculated, backend need to do some benchmarks for this
5. let's consider rebond later.

**Comment by MrPai** [comment]
I will close this issue because we have already started to develop the code according to the new design(stake and get xKSM directly).
and we have other issues tracking it:
#384 
#385 
#386

**Comment by MrPai** [comment]
here is the link about exchange rate improvement, I make some comments inside it,
It seems like we can not simple use "Exchangerate = TotalBondBenefit/TotalLiquidCurrency" calculate the exchangerate, because we can not make sure when to update exchangerate according to rewards records.
https://docs.google.com/spreadsheets/d/1Z1Y4V_7eccqUWioC73BUd6aOjaz9hhSC70KRle_xNec/edit?usp=sharing
