### ISSUE TITLE
Fix stake-client v1

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#356]
**Description**

**Expected behaviour**

- when user stakes, the staked token should be upward transferred to a multi-sig account in relaychain and should be used to nominate some validators

- when user unstake, then bonded tokens should be unbonded and withdrawn to parachain address then give back to user

**Current behaviour**
1. when user stakes, the staked token cannot be upward transferred to the multi-sig account, caused by #345 
2. even if xcm succeeed, the token will not be used to nominate validators

**Reproduce steps**

1. download [heiko-dev.zip](https://github.com/parallel-finance/parallel/files/6935313/heiko-dev.zip)
2. uncompress it to heiko-dev, go to heiko-dev and run `docker-compose up -d --build`, wait until every service works correctly (no restarting containers)
3. run `docker logs -f` on the stake-para-alice container
4. go to https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/ and then set controller key to `//Eve`
5. go to localhost:8080/#/staking and then use `Bob_Stash` to stake some tokens
6. check logs of stake-para-alice container
7. go to https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/ to check `5DjYJStmdZ2rcqXbXGX7TW85JsrW6uG4y9MUcLq2BoPMpRA7`'s balance, if you stake 100, it should has 99.xx
8. check if `5DjYJStmdZ2rcqXbXGX7TW85JsrW6uG4y9MUcLq2BoPMpRA7` nominated some validators
9. go to localhost:8080/#/staking and then use `Bob_Stash` to unstake some tokens like 50
10. go to https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/ to see if the staked tokens will be unbonded, go to  go to https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9947#/ and check the liquidStaking's chainstate to ensure there is `AccountProcessingUnstake`
11. when it's unbonded, check if the unbonded tokens go to `5DjYJStmdZ2rcqXbXGX7TW85JsrW6uG4y9MUcLq2BoPMpRA7` address
12. when the unbonded tokens arrive at `5DjYJStmdZ2rcqXbXGX7TW85JsrW6uG4y9MUcLq2BoPMpRA7` account, check if it'll finally be cross chain transferred to `5EYCAe5iie3Jms55YSqwGAx8H5Yj4Xv84tWYmdbm1sB1EwtZ ` in parachain
13. if yes then check if `KSM` will be given back to `Bob_stash` after that

**Comment by GopherJ** [comment]
1. MIN_BOND_BALANCE is 100
2. AccountProcessingUnstake seems called after withdraw_unbonded
3. ? nominate

**Comment by GopherJ** [comment]
- parallelfinance/parallel-dapp:heiko
- parallelfinance/parallel:latest
- parallelfinance/stake-client:latest
- parallelfinance/nominate-client:latest

**Comment by yz89** [comment]
When you reboot the docker-compose, you should purge the volume.
```
docker-compose down --remove-orphans
docker network prune
docker volume prune
```

**Comment by GopherJ** [comment]
[heiko-dev.zip](https://github.com/parallel-finance/parallel/files/6972265/heiko-dev.zip)
