### ISSUE TITLE
Setup a test environment 

### ISSUE THREAD

**Issue by crystalynliu** [parallel-finance/parallel#372]
**Motivation**

We need a test environment to do testing before deploying changes to production, in order to keep the production to be stable.

**Suggested Solution**

* A discussion about what's the strategy of the test environment, including frontend and backend.
* Setup the test environment.

**Alternatives**

Nope

**Additional Information**

Nope

**Comment by woshihahaha** [comment]
The test environment has been deployed.
Deployment Platform address: https://test-jenkins.parallel.fi(the account has been sent to the email address of the relevant personnel)
Access address: regnet.parallel.fi
Rpc address: regnet-rpc.parallel.fi
