### ISSUE TITLE
study to use parallel-subql

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#373]
**Motivation**

subql started to work, we should learn on how to use it

There are a few questions around this:

- [ ] how to get history data of certain state like `DOT`'s exchangeRate from block1 to block1000, this can be used to draw frontend charts
- [ ] TBD

**Suggested Solution**

Nope

**Alternatives**

Nope

**Additional Information**

Nope

**Comment by ayushmishra2005** [comment]
query {
    exchangeRates (filter:{blockNumber:{greaterThanOrEqualTo: "45000", lessThanOrEqualTo:"46000"} }) {
        nodes {
            id
          rates
        }
    }
}
