### ISSUE TITLE
integrate xcm-simulator

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#377]

**Comment by GopherJ** [comment]
hi @MrPai would you be interested in taking this since you already have experiences on this

**Comment by MrPai** [comment]
yes, of course, how do you think if we integrate the xcm-simulator in LiquidStaking V1 or V2 first? @GopherJ

**Comment by GopherJ** [comment]
I think maybe LiquidStaking V2 @MrPai

**Comment by yz89** [comment]
The `pallet-liquid-staking-v2` will keep depent on stake-client. We can modify and let the `pallet-liquid-staking` support `xcm-transact` now.
