### ISSUE TITLE
Support non-collateral asset to money market

### ISSUE THREAD

**Issue by yubo-ruan** [parallel-finance/parallel#378]
**Motivation**

Many assets in the Polkadot ecosystem are at their early stage and we want to add them to our money market with two steps 
1. Add as non-collateral asset 
2. Turn on as a collateral asset

**Suggested Solution**

1. Add support for a non-collateral asset to be added to our market

**Comment by yz89** [comment]
We only need to set the `collateral_factor` of the market to 0% when adding a new market. Then we can increase this number by governance.

**Comment by yubo-ruan** [comment]
Got it - thanks
