### ISSUE TITLE
prepare parallel polkadot apps PR

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#380]
## Endpoints
https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/endpoints/productionRelayKusama.ts

## Colors
https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/ui/colors.ts

## Logos
https://github.com/polkadot-js/apps/tree/master/packages/apps-config/src/ui/logos/chains
https://github.com/polkadot-js/apps/tree/master/packages/apps-config/src/ui/logos/nodes

## Types
https://github.com/polkadot-js/apps/blob/master/packages/apps-config/package.json#L9
https://github.com/polkadot-js/apps/tree/master/packages/apps-config/src/api/spec

**Comment by kennyykw** [comment]
![logo 200x200](https://user-images.githubusercontent.com/4702705/130338309-d70552c7-a25d-49fb-bd46-4999655bdc1b.png)

**Comment by kennyykw** [comment]
[logo 200x200.svg.zip](https://github.com/parallel-finance/parallel/files/7026397/logo.200x200.svg.zip)

**Comment by GopherJ** [comment]
@kennyykw can you send me also some colors?

**Comment by GopherJ** [comment]
https://github.com/polkadot-js/apps/pull/5989

**Comment by kennyykw** [comment]
@GopherJ  what do you mean by colors here? What colors do you need me to send?

**Comment by GopherJ** [comment]
@kennyykw I've used a blue color

**Comment by kennyykw** [comment]
![HKO](https://user-images.githubusercontent.com/4702705/130556436-fe66ade3-e55a-42be-82b5-8148f19e85a5.png)

@GopherJ can you update the logo? Sorry the last logo I sent was wrong.

**Comment by yubo-ruan** [comment]
@kennyykw Can you actually update it to:

![image](https://user-images.githubusercontent.com/40745291/130557898-8be5a95e-b80b-4e9c-8e57-9e96959e96ba.png)


since this is not token's logo. it is our parachain's logo

**Comment by kennyykw** [comment]
[logo_mark (1).svg.zip](https://github.com/parallel-finance/parallel/files/7036555/logo_mark.1.svg.zip)
@GopherJ

**Comment by GopherJ** [comment]
I'll do it after finishing #442
