### ISSUE TITLE
Implement claim dispatchable for staking v2

### ISSUE THREAD

**Issue by yz89** [parallel-finance/parallel#386]
## Scopes
- [x] add claim call with parameters accountId, ear_index
- [x] calculate the claimable amount. `UnstakeMisc.total_amount / total_unstake_amount * (total_unstake_amount - total_stake_amount)`.
- [x] transfer the claimable amount from pelletId to sender.
- [x] update the UnstakeMisc.claimed_amount
- [ ] unit test

**Comment by MrPai** [comment]
This `claim` call relies on the Matching result, because after the matching mechanism:
for `bond` operation, users who `unstake` can claim all KSM back;
for `unbond` operation, users who `unstake` can only claim partial KSM back.

so we should first know how the matching mechanism store result.

**Comment by yz89** [comment]
The matching result needn't store, for we can easily figure out it.
Maybe we can reuse the `matching` method implementing by @GopherJ, then we can calculate the claimable amount by matching result.

**Comment by GopherJ** [comment]
#405

**Comment by crystalynliu** [comment]
We have a new idea, #432
