### ISSUE TITLE
accountBorrow doesn't match token balance

### ISSUE THREAD

**Issue by yubo-ruan** [parallel-finance/parallel#40]
try deposit DOT and borrow USDT

**Comment by yubo-ruan** [comment]
accountCollateral doesn't match with token balance too

**Comment by yz89** [comment]
The low liquidation_threshold (40%) causes the problem.  
Liquidation will happen automatically when your borrow balance over 40% of your collateral.

**Comment by MrPai** [comment]
ok,  40% is easy for the liquidation test, We can adjust the liquidation_threshold to 90%

**Comment by yz89** [comment]
All right, please modify the TODO comment by the way.

**Comment by MrPai** [comment]
got it, fix it in https://github.com/parallel-finance/parallel/pull/49
please review if fix this bug.
