### ISSUE TITLE
Parachain is not able to fetch price

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#42]
**Description**

![image](https://user-images.githubusercontent.com/33961674/113961774-25493c80-9859-11eb-8afe-f6300075d6b1.png)

**Steps to Reproduce**

_Replace the example steps below with actual steps to reproduce the bug you're reporting._

**Expected vs. Actual Behavior**

_What did you expect to happen after you followed the steps you described in the last section? What
actually happened?_

**Environment**

_Describe the environment in which you encountered this bug. Use the list below as a starting point
and add additional information if you think it's relevant._

- Operating system:
- Template version/tag:
- Rust version (run `rustup show`):

**Logs, Errors or Screenshots**

_Please provide the text of any logs or errors that you experienced; if
applicable, provide screenshots to help illustrate the problem._

**Additional Information**

_Please add any other details that you think may help us solve your problem._

**Comment by MrPai** [comment]
ok, we will test the new Oracle in Parachain.

**Comment by MrPai** [comment]
I think it's because we can not request HTTP URL in a docker container, we should find out how to fix this.

**Comment by yz89** [comment]
You can try '--net=host' when 'docker run'.

**Comment by GopherJ** [comment]
@MrPai @yz89 From my tests, the container can access APIS like: `https://api.coincap.io/v2/assets/tether` but it still cannot fetch prices

**Comment by GopherJ** [comment]
**EDIT**: it's still a container issue as it works on my local machine this morning
![image](https://user-images.githubusercontent.com/33961674/114489897-7df84b00-9c46-11eb-96fe-53b7a6a95825.png)

**Comment by GopherJ** [comment]
https://github.com/parallel-finance/parallel/blob/master/pallets/ocw-oracle/src/lib.rs#L326-L339

**Comment by GopherJ** [comment]
## Reproduce Steps

```
1. git clone https://github.com/parallel-finance/parallel
2. cd parallel
3. git checkout feat/automation
4. ./scripts/build-image
5. docker-compose up -d
```

**Comment by kaichaosun** [comment]
Close it as we are not using ocw to fetch price anymore.
