### ISSUE TITLE
Deploy dev runtime to staging

### ISSUE THREAD

**Issue by kaichaosun** [parallel-finance/parallel#43]
After a PR merged, it should be automatically deploy the dev runtime to staging, so app users can try the new changes.

**Comment by GopherJ** [comment]
I've spent some time reading different solutions:
1. docker/build-push-action@v2+ k8s + keel
2. docker/build-push-action@v2 + dockerhub webhook + webhook handler
3. docker/build-push-action@v2 + appleboy/ssh-action
