### ISSUE TITLE
adjust liquidstaking on-chain part with xcm-transact

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#440]
**Motivation**

Since XCM v2 is onboarding, we should consider integrating with it in our liquidstaking design.

**Suggested Solution**
- [x] deploy westend relaychain and heiko parachain
- [x] do some research and test about transact
- [x] integrate with [xcm-simulator](https://github.com/shaunxw/xcm-simulator) in XCM test code
- [x] write document about xcm-v2
- [x] adjust the design of liquidstaking on-chain part
- [x] discuss with team

**Comment by MrPai** [comment]
refer to #326

**Comment by MrPai** [comment]
Success: transact from parachain code, invoke relaychain "system.remark"
![1 transact_remark_success.jpg](https://images.zenhubusercontent.com/60ebb64e19e4766b543eeb3e/e14dda41-031d-43e8-a290-d6dc584243a6)

**Comment by MrPai** [comment]
Failed: transact failed from parachain, invoke relaychain `staking.bond`
![2 transact_failed_bond.jpg](https://images.zenhubusercontent.com/60ebb64e19e4766b543eeb3e/eba92850-215d-4e9a-b155-2f187b9f2e42)

**Comment by MrPai** [comment]
Success: transact success from parachain via XCM message, invoke relaychain `staking.bond`
![3 transact_success.jpg](https://images.zenhubusercontent.com/60ebb64e19e4766b543eeb3e/6dfaf283-e15c-43c0-a65c-df0ce4f3a9bc)

**Comment by MrPai** [comment]
## XCM Overview
**XCM-v0** 
xcm-v0 now works on Kusama, the version is [ release-v0.9.9](https://github.com/paritytech/polkadot/blob/release-v0.9.9/xcm/Cargo.toml).
**XCM-v1** 
xcm-v1 has been raised in this [PR-2815](https://github.com/paritytech/polkadot/pull/2815), and the newest version located [here](https://github.com/paritytech/polkadot/tree/30a6c7fc3a850f598f2ab61252a6647d017f89a5/xcm).
**XCM-v2**
xcm-v2 has been improved a lot, the design concept is different from v0/v1, related [PR-3629](https://github.com/paritytech/polkadot/pull/3629).

**Comment by MrPai** [comment]
It seems like xcm-v1 will be included in Polkadot release-v0.9.10, please check this [PR-3763](https://github.com/paritytech/polkadot/pull/3763). its status is draft for now.

**Comment by MrPai** [comment]
Subsequent works will be tracked by #502, will close this issue now.

**Comment by yz89** [comment]
Excellent document 👍
