### ISSUE TITLE
BUG: Type parse error about XCM MultiAssets

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#445]
**Description**

There may be some bug about the type parse in polkadot.js. since this [commit](https://github.com/polkadot-js/apps/commit/64c0488a72e213da7787970449c9611efed3695d) has been merged. then we no need to input type.json manually.

However, I meet a problem when test XCM. when test UMP on parachain side, I can not choose the right argument.
***
- right `MultiAssets` from relaychain side
![type1](https://user-images.githubusercontent.com/26266313/130601282-214d0fd0-baad-4a88-b2a6-97be50447422.jpg)
- wrong `MultiAssets` from parachain side
![type2](https://user-images.githubusercontent.com/26266313/130601296-50e43969-f814-4efd-940f-7b435394e19d.jpg)

**when I only use a former version of [polkadot.js](https://github.com/polkadot-js/apps/releases/tag/v0.95.1) then everything looks good and I can keep on testing XCM**

**Comment by GopherJ** [comment]
emm good to know

**Comment by GopherJ** [comment]
@MrPai I think this one should be reported to polkadotjs apps

**Comment by MrPai** [comment]
polkadotjs works fine when I choose relaychain endpoint but have a type error when choosing parachain endpoint.

**Comment by GopherJ** [comment]
Ref: https://github.com/polkadot-js/api/issues/3903

**Comment by GopherJ** [comment]
I
