### ISSUE TITLE
LP tokens support

### ISSUE THREAD

**Issue by ETeissonniere** [parallel-finance/parallel#488]
Pool's ownership should be represented by a custom LP token.
I am thinking of a custom `CurrencyId` in the form of `LPShare(PalletId, CurrencyId, CurrencyId`.

https://www.notion.so/parallelfinance/LP-Tokens-6e779eaef8d54c58a01c28e2fe378326

**Comment by ashi20192020ayush** [comment]
@ETeissonniere As discussed, We will be doing this task in 2 parts:

1) Modify CurrencyId structure
2) Modify Ownership logic
