### ISSUE TITLE
Investigate the Low-Level implementation about "encode/decode" in XCM transact

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#489]
**Motivation**

About XCM transact, `staking.bond_extra` will succeed however `staking.bond` will fail, and this happens in the decoding process.
the error info is "could not decode RewardDestination"
![not8 1 reward destination](https://user-images.githubusercontent.com/26266313/131253466-11758aef-b821-4047-9f08-b6a81344885d.jpg)

**Suggested Solution**

the former test can be found in #440 

- [x] Investigate the Low-Level implementation about "encode/decode"
- [ ] write document describe the problem

**Comment by GopherJ** [comment]
I think we can post this question to element, maybe someone else can help us because it looks like a known issue

**Comment by MrPai** [comment]
Please refer to this line to know more info about the problem:
https://github.com/MrPai/parallel/blob/release-v0.9.9/pallets/xcm/src/lib.rs#L22
https://github.com/paritytech/substrate/blob/polkadot-v0.9.9/frame/staking/src/pallet/mod.rs#L682
Now `staking.bond` can success too in test environment.

 At first, on parachain side the type of `Controller` is `AccountId`, however on relaychain side, the type of `Controller` is `<T::Lookup as StaticLookup>::Source`, this is actually an Enum type.
so if parachain side encode it as an accountId, relaychain side will decode it wrong.

**Comment by MrPai** [comment]
It works in the test environment(xcm-simulator), will test it on-chain
![staking.bond success.jpg](https://images.zenhubusercontent.com/60ebb64e19e4766b543eeb3e/04a1acb1-af0e-44bf-a29f-10831409341e)

**Comment by MrPai** [comment]
## Staking.bond bug in XCM.transact
### Context
Here is the [staking.bond](https://github.com/paritytech/substrate/blob/polkadot-v0.9.9/frame/staking/src/pallet/mod.rs#L680-L685) method on relaychain, its parameter is 
>pub fn bond(
			 origin: OriginFor<T>,
			controller: <T::Lookup as StaticLookup>::Source,
			#[pallet::compact] value: BalanceOf<T>,
			payee: RewardDestination<T::AccountId>,
		)
> 
and below is on parachain, we use [StakingBondCall](https://github.com/MrPai/parallel/blob/5068789281/pallets/xcm/src/lib.rs#L20-L26) struct store the arguments, and then send it to relaychain via [XCM.transact](https://github.com/MrPai/parallel/blob/5068789281/pallets/xcm/src/lib.rs#L116-L166).
> #[derive(Encode, Decode)]
pub struct StakingBondCall<T: Config> {
    call_index: [u8; 2],
    controller: T::AccountId,
    #[codec(compact)]
    value: Balance,
    payee: RewardDestination<T::AccountId>,
}
> 

### Bug details
Here directly point out the bug, from above, on relaychain side, it needs `controller` to be a type `<T::Lookup as StaticLookup>::Source`, this is actually an Enum type [MultiAddress](https://github.com/paritytech/substrate/blob/polkadot-v0.9.9/primitives/runtime/src/traits.rs#L250), type [Lookup](https://github.com/paritytech/polkadot/blob/release-v0.9.9/runtime/westend/src/lib.rs#L166).

but on parachain, the `controller` is simply a `T::AccountId` type. 
this will lead to `encode/decode` wrong between parachain and relaychain.
### Fix
on parachain, the `StakingBondCall` should keep same with relaychain.
>pub struct StakingBondCall<T: Config> {
    call_index: [u8; 2],
    controller: <T::Lookup as StaticLookup>::Source,
    #[codec(compact)]
    value: Balance,
    payee: RewardDestination<T::AccountId>,
}
>

### Encode/Decode details
Here is the [link](https://substrate.dev/docs/en/knowledgebase/advanced/codec#enumerations-tagged-unions) that shows how SCALE encode/decode an Enum type.
Enum type need one more byte to store its index.
