### ISSUE TITLE
Assets registry pallet

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#590]

**Comment by GopherJ** [comment]
Ref: https://github.com/AcalaNetwork/Acala/blob/master/modules/asset-registry/src/lib.rs

**Comment by GopherJ** [comment]
statemine: https://github.com/paritytech/cumulus/blob/master/polkadot-parachains/statemine/src/xcm_config.rs#L81-L87

**Comment by GopherJ** [comment]
## Config

## Storage

## Call

**Comment by rocketman1997** [comment]
would assume this module mainly targets at adding foreigner assets from other chains by xcm without code change, if so would suggest we also check Moonbeam's [asset-manager](https://github.com/PureStake/moonbeam/blob/master/pallets/asset-manager/src/lib.rs) module as reference, except for make hard-coded [Asset<->MultiLocation](https://github.com/parallel-finance/parallel/blob/ac03b16f8882ebf1399ea4e4f69df06c9495a9f1/runtime/heiko/src/lib.rs#L346-L433) configurable we can also change the [Asset->UnitsPerSecond](https://github.com/parallel-finance/parallel/blob/ac03b16f8882ebf1399ea4e4f69df06c9495a9f1/runtime/heiko/src/lib.rs#L988-L1039) mapping structure as configurable, then we can refact the [trader](https://github.com/parallel-finance/parallel/blob/ac03b16f8882ebf1399ea4e4f69df06c9495a9f1/runtime/heiko/src/lib.rs#L1070-L1071) a bit clean like [that](https://github.com/PureStake/moonbeam/blob/ad5e1377105053f65b3e2296edd9310bd9a1100a/runtime/moonriver/src/lib.rs#L1152)
