### ISSUE TITLE
Make launch failed with master branch

### ISSUE THREAD

**Issue by alannotnerd** [parallel-finance/parallel#619]
**Description**
Make launch failed

**Steps to Reproduce**
- clone the repo
- cd project root
- make launch

**Expected vs. Actual Behavior**
docker compose started

**Environment**

Ubuntu18.04

**Logs, Errors or Screenshots**
![image](https://user-images.githubusercontent.com/24879490/133922827-e09e44e7-efb7-436c-b199-dddcfb8e777e.png)

**Additional Information**

Maybe somewhere appends a mistake "/"

**Comment by GopherJ** [comment]
close via: #620
