### ISSUE TITLE
Refactor AMM, currency-adapter, router pallet to use AssetIdOf, BalanceOf

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#644]

**Comment by yz89** [comment]
Let's deprecate the AssetIdOf, BalanceOf in loans/staking pallet. This type derivation is unnecessary and complicates the code.

**Comment by GopherJ** [comment]
the current AMM, currency_adapter also looks horrible:

```
        type Assets: Transfers<Self::AccountId, AssetId = AssetId, Balance = Balance>
            + Inspects<Self::AccountId, AssetId = AssetId, Balance = Balance>
            + Mutates<Self::AccountId, AssetId = AssetId, Balance = Balance>;

        type Balances: fungible::Inspect<Self::AccountId, Balance = Balance>
            + fungible::Mutate<Self::AccountId, Balance = Balance>
            + fungible::Transfer<Self::AccountId, Balance = Balance>;
```

**Comment by GopherJ** [comment]
and it's not general, this pallet is linked to other pallet `primitives` which may not be a good thing

**Comment by yz89** [comment]
Yes, CurrencyAdapter should be generic. Agree with you.

**Comment by ETeissonniere** [comment]
We need to agree on a pattern for the repo in general. The normal substrate way is to use `BalanceOf`, `AssetIdOf` etc to make things easier to plug in.

However, if we agree on a pattern, we need all the pallets to follow it otherwise things will get messy quickly.

**Comment by GopherJ** [comment]
Yes I personally prefer using `BalanceOf`, `AssetIdOf`

**Comment by ETeissonniere** [comment]
Just discussed on TG. Our decision is to adopt the substrate pattern and refactor the impacted pallets.
