### ISSUE TITLE
improve README.md

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#68]
example:
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/33961674/115818161-c5dd5600-a42e-11eb-8e0f-7b4854ded93d.png">

**Comment by yz89** [comment]
I love the style 💯

**Comment by GopherJ** [comment]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/33961674/115946440-bbd15b00-a4f3-11eb-949d-99a8ef28aad7.png">

**Comment by yz89** [comment]
via fc53d38
