### ISSUE TITLE
add tokenDecimals, tokenSymbol to chainspec

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#72]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/33961674/115983372-463cbc00-a5d3-11eb-9c42-9a3f7d78fa06.png">

**Comment by GopherJ** [comment]
https://github.com/AcalaNetwork/Acala/blob/ffab9282f9b3cf26e211aba5a17332a709e118ae/bin/acala/service/src/chain_spec/mandala.rs#L84-L93

**Comment by alannotnerd** [comment]
I think it's done with #321

**Comment by yz89** [comment]
Yes, well done.
