### ISSUE TITLE
Dockerfile.dev file to support cargo cache

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#727]

**Comment by drbh** [comment]
researching approaches to allow caching. 

### Relevant links
Long term conversation (very informative)
https://github.com/rust-lang/cargo/issues/2644

Promising tool
https://github.com/LukeMathWalker/cargo-chef

Possible implementation using Docker BuildKit
https://www.noelbundick.com/gists/optimizing-rust-container-builds/

Similar implementation for parity project
https://gitlab.parity.io/parity/parity-bridges-common/-/commit/352dc686aeeeeba5f384ac213b4b1338e53a6632

I'm currently working on adding a `Dockerfile.dev` that is similar to the `parity-bridges-common` implementation. Will open a PR today
