### ISSUE TITLE
currency_id abstration

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#74]
heiko & parallel have different markets KSM versus DOT, but these two runtimes share the same pallets. We need to have an abstration layer on this so that we don't need to have two same pallets.

**Comment by MrPai** [comment]
I draw a [flow chart](https://www.processon.com/view/link/60842c8af346fb54941c0f6e) before, maybe we can discuss it, to see if it's ok.

**Comment by GopherJ** [comment]
https://github.com/AcalaNetwork/Acala/blob/e2e5131f32ae7ea1544639ecc2bba6414e73a920/primitives/src/currency.rs
