### ISSUE TITLE
add call to increase insurance

### ISSUE THREAD

**Issue by 0x8f701** [parallel-finance/parallel#743]
just burn KSM and put it into insurance pool so that parachain account on relaychain can have such amount of KSM to pay xcm fees

**Comment by MrPai** [comment]
The process may look like this:
1. Alice on relaychain call `dmp` transfer, send KSM from relaychain to parachain Alice account,
2. Alice on parachain invoke `increase insurance` call,
3. Alice on parachain transfer her KSM to the `liquidstaking pallet account` KSM, increase the `insurance pool` amount.
