### ISSUE TITLE
Integrate chainlink oracle pallet

### ISSUE THREAD

**Issue by yz89** [parallel-finance/parallel#824]

**Comment by MrPai** [comment]
https://github.com/smartcontractkit/chainlink-polkadot

**Comment by MrPai** [comment]
## Consider
- mint LINK currency in `pallet-asset`
- simultaneously use  both `orml-oracle` and `chainlink-oracle`?

**Comment by yz89** [comment]
How to launch the off-chain nodes?

**Comment by MrPai** [comment]
<img width="973" alt="WeChat92ea7945d21d63afe0f9da02f7481364" src="https://user-images.githubusercontent.com/26266313/147095983-9f32708b-af4c-410e-bbbf-20c7fad5c65b.png">
