### ISSUE TITLE
Bump parallel-js

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#856]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/33961674/140253537-8ec3b892-8b1b-4af0-bc50-726f39741e86.png">

**Comment by GopherJ** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/33961674/140253573-93f91375-d560-4332-bd0f-d79f1b3aa6e3.png">

**Comment by yz89** [comment]
https://github.com/polkadot-js/api/issues/4216
https://github.com/polkadot-js/api/issues/4213
https://github.com/polkadot-js/api/pull/4224

**Comment by GopherJ** [comment]
https://github.com/polkadot-js/api/issues/4481
https://github.com/AcalaNetwork/acala.js/pull/265
https://github.com/polkadot-js/api/issues/4525
