### ISSUE TITLE
Not able to execute benchmarking with `parallel` and `vanilla` chain_spec

### ISSUE THREAD

**Issue by ashi20192020** [parallel-finance/parallel#862]
**Description**

Not able to execute benchmarking with with `parallel` and `vanilla` chain_spec. PR https://github.com/parallel-finance/parallel/pull/829 is causing this issue. 
Getting below error
```
Error: Input("Error getting benchmark list: Other(\"Exported method Benchmark_benchmark_metadata is not found\")")
```

**Steps to Reproduce**

Execute below command
```
cargo run --release --features=runtime-benchmarks --bin parallel -- benchmark --chain=parallel-dev --steps=50 --repeat=20 --pallet=pallet_amm --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./pallets/amm/src/weights.rs --template=./.maintain/frame-weight-template.hbs
```

**Additional Information**

However if we change chain-spec name for ex: `--chain=parallel-dev`, it works fine.

**Comment by GopherJ** [comment]
@ashi20192020ayush if `parallel-dev` works then it should be fine, because the difference between `parallel` and `parallel-dev` is the genesis. 

benchmarks should only differ on runtime but `parallel-dev` & `parallel` shares the same runtime
