### ISSUE TITLE
HKO, PARA's decimal provider

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#897]
if we want to lend HKO/PARA in money market they should have a decimal. The current decimal provider uses Assets' metadata but native tokens are not an asset yet.

- if we want to lend HKO/PARA, then we will need to register a new asset HKO/PARA => should be ok, we have CurrencyAdapter, but how to prevent transfer via Assets because it makes nosense

**Comment by yz89** [comment]
Money market won't lend the ptoken ever. Instead, ptokens are derivatives of other deposit currencies.

**Comment by GopherJ** [comment]
> Money market won't lend the ptoken ever. Instead, ptokens are derivatives of other deposit currencies.

yes, then it's cyclic if we do so

**Comment by GopherJ** [comment]
Looks like native tokens' decimal should be managed by Assets module so that we dont need to create an asset
