### ISSUE TITLE
Is it necessary to delete storage after expiration

### ISSUE THREAD

**Issue by rjman-ljm** [parallel-finance/parallel#929]
**Question**

If the storage is deleted after expire, it will bring some business troubles because we can't get the past status of proposal, so we may need a centralized database to store all the history.

1. For successfully completed cross-chain transactions, the storage is also the history of the transactions, which should be kept on the chain, and if deleted, users can only query the history through the centralized database if they want to do so.
2. For proposals that fail to complete voting in time, I think voting should be continued after the relayer is recovered, instead of deleting the storage, which would create an additional business requirement: rolling back the funds deposited by users.

**Possible solutions**

1. A very long expiry time, maybe two weeks or a month.
  > Relayer can resolve these cross-chain transactions without troubles, as there is a long time to query the storage.
  > However, history is also lost when it expires and users cannot check their records on-chain.
2. No expiration time, and every cross-chain transaction should always be guaranteed to be completed.

Please correct me if I have misunderstood something.

**document**

[notion link](https://www.notion.so/parallelfinance/Bridge-to-ETH-241c6367d41d4843ba081258056e29bf)

**Comment by ETeissonniere** [comment]
I think option 1 seems to make the most sense. The problem 2 could indeed be an issue, a reasonably long expiry time should be able to clear that up.

The point of cleaning the storage for completed (or expired) transactions is to keep the on-chain state small. Typically it is bad practice to keep some state that we no longer need or use, it creates bloat. We already have a SubQL indexer along with the ability to query the on-chain storage for any past block (exposed via the standard APIs of the node) if needed. This is what we should use if we ever want to query historical data, for instance to represent it in a block explorer.

**Comment by rjman-ljm** [comment]
Okay
